--------------------------------------------------------
--  DDL for Table REVIEWS_HISTORY
--------------------------------------------------------

  CREATE TABLE "REVIEWS_HISTORY" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR), 
	"ACTIVITYTYPE" VARCHAR2(45 CHAR), 
	"COLUMNNAME" VARCHAR2(45 CHAR), 
	"OLDVALUE" VARCHAR2(32766 CHAR), 
	"NEWVALUE" VARCHAR2(32766 CHAR), 
	"USERID" NUMBER(10,0), 
	"TS" DATE DEFAULT SYSDATE
   ) ;
--------------------------------------------------------
--  DDL for Table REVIEWS
--------------------------------------------------------

  CREATE TABLE "REVIEWS" 
   (	"REVIEWID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR), 
	"STATEID" NUMBER(10,0), 
	"USERID" NUMBER(10,0), 
	"STATECOMMENT" VARCHAR2(32766 CHAR), 
	"ACTIONID" NUMBER(10,0), 
	"ACTIONCOMMENT" VARCHAR2(32766 CHAR), 
	"REQDOC" NUMBER(3,0) DEFAULT '0', 
	"AUTOSTATE" NUMBER(3,0) DEFAULT '0', 
	"TS" DATE DEFAULT SYSDATE, 
	"REJECTTEXT" VARCHAR2(32766 CHAR), 
	"REJECTUSERID" NUMBER(10,0), 
	"STATUSID" NUMBER(10,0) DEFAULT '0'
   ) ;
--------------------------------------------------------
--  DDL for Table ACTIONS
--------------------------------------------------------

  CREATE TABLE "ACTIONS" 
   (	"ACTIONID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ACTION" VARCHAR2(45 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table ASSET_PACKAGE_MAP
--------------------------------------------------------

  CREATE TABLE "ASSET_PACKAGE_MAP" 
   (	"APID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"PACKAGEID" NUMBER(10,0), 
	"SCANRESULTID" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table ARTIFACT_BLOBS
--------------------------------------------------------

  CREATE TABLE "ARTIFACT_BLOBS" 
   (	"SHA1" VARCHAR2(45 CHAR), 
	"DATA" BLOB, 
	"TS" DATE DEFAULT SYSDATE, 
	"USERID" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table STATES
--------------------------------------------------------

  CREATE TABLE "STATES" 
   (	"STATEID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STATE" VARCHAR2(45 CHAR), 
	"ABBR" VARCHAR2(3 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table STATS_ASSET_STIG
--------------------------------------------------------

  CREATE TABLE "STATS_ASSET_STIG" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"STIGID" VARCHAR2(255 CHAR), 
	"MINTS" DATE, 
	"MAXTS" DATE, 
	"CHECKSMANUAL" NUMBER(10,0), 
	"CHECKSSCAP" NUMBER(10,0), 
	"INPROGRESSMANUAL" NUMBER(10,0), 
	"INPROGRESSSCAP" NUMBER(10,0), 
	"SUBMITTEDMANUAL" NUMBER(10,0), 
	"SUBMITTEDSCAP" NUMBER(10,0), 
	"REJECTEDMANUAL" NUMBER(10,0), 
	"REJECTEDSCAP" NUMBER(10,0), 
	"APPROVEDMANUAL" NUMBER(10,0), 
	"APPROVEDSCAP" NUMBER(10,0), 
	"CAT1COUNT" NUMBER(10,0), 
	"CAT2COUNT" NUMBER(10,0), 
	"CAT3COUNT" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table REJECT_STRINGS
--------------------------------------------------------

  CREATE TABLE "REJECT_STRINGS" 
   (	"REJECTID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SHORTSTR" VARCHAR2(45 CHAR), 
	"LONGSTR" VARCHAR2(32766 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "ROLES" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROLE" VARCHAR2(45 CHAR), 
	"ROLEDISPLAY" VARCHAR2(45 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table REVIEW_REJECT_STRING_MAP
--------------------------------------------------------

  CREATE TABLE "REVIEW_REJECT_STRING_MAP" 
   (	"RRSID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR), 
	"REJECTID" NUMBER(10,0), 
	"USERID" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table STIG_ASSET_MAP
--------------------------------------------------------

  CREATE TABLE "STIG_ASSET_MAP" 
   (	"SAID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STIGID" VARCHAR2(255 CHAR), 
	"ASSETID" NUMBER(10,0), 
	"DISABLEIMPORTS" NUMBER(3,0) DEFAULT '0'
   ) ;
--------------------------------------------------------
--  DDL for Table REVIEW_ARTIFACT_MAP
--------------------------------------------------------

  CREATE TABLE "REVIEW_ARTIFACT_MAP" 
   (	"RAID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR), 
	"ARTID" NUMBER(10,0), 
	"USERID" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table ARTIFACTS
--------------------------------------------------------

  CREATE TABLE "ARTIFACTS" 
   (	"ARTID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SHA1" VARCHAR2(45 CHAR), 
	"FILENAME" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"USERID" NUMBER(10,0), 
	"TS" DATE DEFAULT SYSDATE, 
	"DEPT" VARCHAR2(45 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table PACKAGES
--------------------------------------------------------

  CREATE TABLE "PACKAGES" 
   (	"PACKAGEID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(45 CHAR), 
	"BOUNDARYID" VARCHAR2(45 CHAR), 
	"EMASSID" VARCHAR2(45 CHAR), 
	"REQRAR" NUMBER(3,0), 
	"POCNAME" VARCHAR2(50 CHAR), 
	"POCEMAIL" VARCHAR2(50 CHAR), 
	"POCPHONE" VARCHAR2(50 CHAR), 
	"MACCLID" NUMBER(10,0), 
	"REPOSITORYID" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table ASSETS
--------------------------------------------------------

  CREATE TABLE "ASSETS" 
   (	"ASSETID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(45 CHAR), 
	"PROFILE" VARCHAR2(45 CHAR) DEFAULT 'MAC-3_Sensitive', 
	"DOMAIN" VARCHAR2(45 CHAR), 
	"IP" VARCHAR2(45 CHAR), 
	"DEPT" VARCHAR2(45 CHAR), 
	"NONNETWORK" CHAR(1) DEFAULT 0, 
	"SCANEXEMPT" CHAR(1) DEFAULT 0
   ) ;
--------------------------------------------------------
--  DDL for Table POAM_RAR_ENTRIES
--------------------------------------------------------

  CREATE TABLE "POAM_RAR_ENTRIES" 
   (	"PREID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PACKAGEID" NUMBER(10,0), 
	"FINDINGTYPE" VARCHAR2(50 CHAR), 
	"SOURCEID" VARCHAR2(45 CHAR), 
	"IACONTROL" VARCHAR2(45 CHAR), 
	"STATUS" VARCHAR2(45 CHAR), 
	"POC" VARCHAR2(255 CHAR), 
	"RESOURCES" VARCHAR2(255 CHAR), 
	"COMPDATE" DATE, 
	"MILESTONE" VARCHAR2(32766 CHAR), 
	"POAMCOMMENT" VARCHAR2(32766 CHAR), 
	"LIKELIHOOD" VARCHAR2(50 CHAR), 
	"MITDESC" VARCHAR2(32766 CHAR), 
	"RESIDUALRISK" NUMBER(10,0), 
	"RECCORRACT" VARCHAR2(32766 CHAR), 
	"REMDESC" VARCHAR2(32766 CHAR), 
	"RARCOMMENT" VARCHAR2(32766 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table STATUSES
--------------------------------------------------------

  CREATE TABLE "STATUSES" 
   (	"STATUSID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STATUSSTR" VARCHAR2(45 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table USER_DATA
--------------------------------------------------------

  CREATE TABLE "USER_DATA" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CN" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"DEPT" VARCHAR2(45 CHAR), 
	"ROLEID" NUMBER(10,0), 
	"CANADMIN" NUMBER(3,0) DEFAULT '0'
   ) ;
--------------------------------------------------------
--  DDL for Table USER_STIG_ASSET_MAP
--------------------------------------------------------

  CREATE TABLE "USER_STIG_ASSET_MAP" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" NUMBER(10,0), 
	"SAID" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Index INDEX_ACTIVITYTYPE
--------------------------------------------------------

  CREATE INDEX "INDEX_ACTIVITYTYPE" ON "REVIEWS_HISTORY" ("ACTIVITYTYPE") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_ASSETID
--------------------------------------------------------

  CREATE INDEX "INDEX_ASSETID" ON "REVIEWS_HISTORY" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_COLUMNNAME
--------------------------------------------------------

  CREATE INDEX "INDEX_COLUMNNAME" ON "REVIEWS_HISTORY" ("COLUMNNAME") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_RULEID
--------------------------------------------------------

  CREATE INDEX "INDEX_RULEID" ON "REVIEWS_HISTORY" ("RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_28
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_28" ON "REVIEWS_HISTORY" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_4
--------------------------------------------------------

  CREATE INDEX "INDEX_4" ON "REVIEWS" ("STATEID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_27
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_27" ON "REVIEWS" ("REVIEWID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3_3
--------------------------------------------------------

  CREATE INDEX "INDEX_3_3" ON "REVIEWS" ("RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_STATUSID
--------------------------------------------------------

  CREATE INDEX "INDEX_STATUSID" ON "REVIEWS" ("STATUSID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_1_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX_2_1_1" ON "REVIEWS" ("ASSETID", "RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY" ON "ACTIONS" ("ACTIONID") 
  ;
--------------------------------------------------------
--  DDL for Index ASSET_PACKAGE_MAP_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSET_PACKAGE_MAP_INDEX1" ON "ASSET_PACKAGE_MAP" ("PACKAGEID", "ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index ASSET_PACKAGE_MAP_INDEX2
--------------------------------------------------------

  CREATE INDEX "ASSET_PACKAGE_MAP_INDEX2" ON "ASSET_PACKAGE_MAP" ("SCANRESULTID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3_1
--------------------------------------------------------

  CREATE INDEX "INDEX_3_1" ON "ASSET_PACKAGE_MAP" ("PACKAGEID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_8
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_8" ON "ASSET_PACKAGE_MAP" ("APID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_2
--------------------------------------------------------

  CREATE INDEX "INDEX_2_2" ON "ASSET_PACKAGE_MAP" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_5
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_5" ON "ARTIFACT_BLOBS" ("SHA1") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_30
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_30" ON "STATES" ("STATEID") 
  ;
--------------------------------------------------------
--  DDL for Index FK_STATS_ASSET_STIG_2
--------------------------------------------------------

  CREATE INDEX "FK_STATS_ASSET_STIG_2" ON "STATS_ASSET_STIG" ("STIGID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_31
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_31" ON "STATS_ASSET_STIG" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_2_C
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX_2_2_C" ON "STATS_ASSET_STIG" ("ASSETID", "STIGID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_24
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_24" ON "REJECT_STRINGS" ("REJECTID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_29
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_29" ON "ROLES" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX2
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX2" ON "REVIEW_REJECT_STRING_MAP" ("ASSETID", "RULEID", "REJECTID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_26
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_26" ON "REVIEW_REJECT_STRING_MAP" ("RRSID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_38
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_38" ON "STIG_ASSET_MAP" ("SAID") 
  ;
--------------------------------------------------------
--  DDL for Index FK_STIGASSETMAP_1
--------------------------------------------------------

  CREATE INDEX "FK_STIGASSETMAP_1" ON "STIG_ASSET_MAP" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index DISABLEIMPORTS
--------------------------------------------------------

  CREATE INDEX "DISABLEIMPORTS" ON "STIG_ASSET_MAP" ("DISABLEIMPORTS") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_3_C
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX_2_3_C" ON "STIG_ASSET_MAP" ("STIGID", "ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_1
--------------------------------------------------------

  CREATE INDEX "INDEX_2_1" ON "REVIEW_ARTIFACT_MAP" ("ASSETID", "RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3
--------------------------------------------------------

  CREATE INDEX "INDEX_3" ON "REVIEW_ARTIFACT_MAP" ("ARTID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_25
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_25" ON "REVIEW_ARTIFACT_MAP" ("RAID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_SHA1
--------------------------------------------------------

  CREATE INDEX "INDEX_SHA1" ON "ARTIFACTS" ("SHA1") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_6
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_6" ON "ARTIFACTS" ("ARTID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_22
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_22" ON "PACKAGES" ("PACKAGEID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_PROFILE
--------------------------------------------------------

  CREATE INDEX "INDEX_PROFILE" ON "ASSETS" ("PROFILE") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_NONNETWORK
--------------------------------------------------------

  CREATE INDEX "INDEX_NONNETWORK" ON "ASSETS" ("NONNETWORK") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_SCANEXEMPT
--------------------------------------------------------

  CREATE INDEX "INDEX_SCANEXEMPT" ON "ASSETS" ("SCANEXEMPT") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_9
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_9" ON "ASSETS" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_DEPT
--------------------------------------------------------

  CREATE INDEX "INDEX_DEPT" ON "ASSETS" ("DEPT") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX_NAME" ON "ASSETS" ("NAME") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_23
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_23" ON "POAM_RAR_ENTRIES" ("PREID") 
  ;
--------------------------------------------------------
--  DDL for Index PACKAGEID_RULEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PACKAGEID_RULEID" ON "POAM_RAR_ENTRIES" ("PACKAGEID", "SOURCEID") 
  ;
--------------------------------------------------------
--  DDL for Index FINDINGTYPE
--------------------------------------------------------

  CREATE INDEX "FINDINGTYPE" ON "POAM_RAR_ENTRIES" ("FINDINGTYPE") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_32
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_32" ON "STATUSES" ("STATUSID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3_C
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX_3_C" ON "USER_DATA" ("NAME") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_35
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_35" ON "USER_DATA" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_CN
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX_CN" ON "USER_DATA" ("CN") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_1_C
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX_2_1_C" ON "USER_STIG_ASSET_MAP" ("USERID", "SAID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3_2
--------------------------------------------------------

  CREATE INDEX "INDEX_3_2" ON "USER_STIG_ASSET_MAP" ("SAID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_3
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_3" ON "USER_STIG_ASSET_MAP" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Trigger REVIEWS_AINS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "REVIEWS_AINS" 
AFTER INSERT ON stigman.REVIEWS
FOR EACH ROW

BEGIN
 	IF :NEW.stateId IS NOT NULL THEN
		INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,newValue,userId)
		VALUES (:NEW.assetId,:NEW.ruleId,'insert','stateId',:NEW.stateId,:NEW.userId);
	END IF;
	IF :NEW.stateComment IS NOT NULL THEN
		INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,newValue,userId)
		VALUES (:NEW.assetId,:NEW.ruleId,'insert','stateComment',:NEW.stateComment,:NEW.userId);
	END IF;
	IF :NEW.actionId IS NOT NULL THEN
		INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,newValue,userId)
		VALUES (:NEW.assetId,:NEW.ruleId,'insert','actionId',:NEW.actionId,:NEW.userId);
	END IF;
	IF :NEW.actionComment IS NOT NULL THEN
		INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,newValue,userId)
		VALUES (:NEW.assetId,:NEW.ruleId,'insert','actionComment',:NEW.actionComment,:NEW.userId);
	END IF;
END;
/
ALTER TRIGGER "REVIEWS_AINS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REVIEWS_AUPD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "REVIEWS_AUPD" 
AFTER UPDATE ON stigman.REVIEWS
FOR EACH ROW
BEGIN
        IF (NVL(:NEW.stateId,0) != NVL(:OLD.stateId,0)) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','stateId',:OLD.stateId,:NEW.stateId,:NEW.userId);
        END IF;

        IF (NVL(:NEW.statusId,0) != NVL(:OLD.statusId,0)) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','statusId',:OLD.statusId,:NEW.statusId,:NEW.userId);
        END IF;

        IF (NVL(:NEW.stateComment,'0') != NVL(:OLD.stateComment,'0')) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','stateComment',:OLD.stateComment,:NEW.stateComment,:NEW.userId);
        END IF;

        IF (NVL(:NEW.actionId,0) != NVL(:OLD.actionId,0)) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','actionId',:OLD.actionId,:NEW.actionId,:NEW.userId);
        END IF;

        IF (NVL(:NEW.actionComment,'0') != NVL(:OLD.actionComment,'0')) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','actionComment',:OLD.actionComment,:NEW.actionComment,:NEW.userId);
        END IF;

        IF (NVL(:NEW.rejectText,'0') != NVL(:OLD.rejectText,'0')) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','rejectText',:OLD.rejectText,:NEW.rejectText,:NEW.userId);
        END IF;
END;
/
ALTER TRIGGER "REVIEWS_AUPD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REVIEWS_BUPD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "REVIEWS_BUPD" 
BEFORE UPDATE ON stigman.REVIEWS
FOR EACH ROW
BEGIN
	IF (:NEW.stateId = 2 OR :NEW.stateId = 3) THEN
		:NEW.actionId := NULL;
		:NEW.actionComment := NULL;
	END IF;
	:NEW.ts := SYSDATE;
END;
/
ALTER TRIGGER "REVIEWS_BUPD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PACKAGES_AUPD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PACKAGES_AUPD" 
AFTER UPDATE OF REPOSITORYID ON stigman.PACKAGES
FOR EACH ROW
BEGIN
  IF (
    :new.repositoryId is null or
    (:old.repositoryId is not null and :new.repositoryId != :old.repositoryId))
  THEN
    UPDATE stigman.ASSET_PACKAGE_MAP SET SCANRESULTID=NULL WHERE PACKAGEID = :new.packageId;
  END IF;
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
ALTER TRIGGER "PACKAGES_AUPD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ASSETS_AUPD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSETS_AUPD" 
AFTER UPDATE OF IP,SCANEXEMPT ON stigman.ASSETS
FOR EACH ROW
BEGIN
  IF (
    (:NEW.ip is null
    AND :OLD.ip is not null)
    OR
    (:NEW.ip is not null AND
    :OLD.ip is not null AND
    :NEW.ip != :OLD.ip)
    OR
    (:NEW.SCANEXEMPT != :OLD.SCANEXEMPT AND
    :NEW.SCANEXEMPT = 1)
  )
  THEN
    UPDATE stigman.ASSET_PACKAGE_MAP SET SCANRESULTID=NULL WHERE ASSETID=:NEW.assetId;
  END IF;
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
ALTER TRIGGER "ASSETS_AUPD" ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEWS_HISTORY
--------------------------------------------------------

  ALTER TABLE "REVIEWS_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "REVIEWS_HISTORY" ADD CONSTRAINT "PRIMARY_28" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEWS
--------------------------------------------------------

  ALTER TABLE "REVIEWS" MODIFY ("REVIEWID" NOT NULL ENABLE);
  ALTER TABLE "REVIEWS" MODIFY ("TS" NOT NULL ENABLE);
  ALTER TABLE "REVIEWS" MODIFY ("STATUSID" NOT NULL ENABLE);
  ALTER TABLE "REVIEWS" ADD CONSTRAINT "INDEX_2_1_1" UNIQUE ("ASSETID", "RULEID")
  USING INDEX  ENABLE;
  ALTER TABLE "REVIEWS" ADD CONSTRAINT "PRIMARY_27" PRIMARY KEY ("REVIEWID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTIONS
--------------------------------------------------------

  ALTER TABLE "ACTIONS" MODIFY ("ACTIONID" NOT NULL ENABLE);
  ALTER TABLE "ACTIONS" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "ACTIONS" ADD CONSTRAINT "PRIMARY" PRIMARY KEY ("ACTIONID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSET_PACKAGE_MAP
--------------------------------------------------------

  ALTER TABLE "ASSET_PACKAGE_MAP" MODIFY ("APID" NOT NULL ENABLE);
  ALTER TABLE "ASSET_PACKAGE_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "ASSET_PACKAGE_MAP" MODIFY ("PACKAGEID" NOT NULL ENABLE);
  ALTER TABLE "ASSET_PACKAGE_MAP" ADD CONSTRAINT "PRIMARY_8" PRIMARY KEY ("APID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTIFACT_BLOBS
--------------------------------------------------------

  ALTER TABLE "ARTIFACT_BLOBS" MODIFY ("SHA1" NOT NULL ENABLE);
  ALTER TABLE "ARTIFACT_BLOBS" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "ARTIFACT_BLOBS" ADD CONSTRAINT "PRIMARY_5" PRIMARY KEY ("SHA1")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATES
--------------------------------------------------------

  ALTER TABLE "STATES" MODIFY ("STATEID" NOT NULL ENABLE);
  ALTER TABLE "STATES" ADD CONSTRAINT "PRIMARY_30" PRIMARY KEY ("STATEID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATS_ASSET_STIG
--------------------------------------------------------

  ALTER TABLE "STATS_ASSET_STIG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STATS_ASSET_STIG" ADD CONSTRAINT "PRIMARY_31" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "STATS_ASSET_STIG" ADD CONSTRAINT "INDEX_2_2_C" UNIQUE ("ASSETID", "STIGID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REJECT_STRINGS
--------------------------------------------------------

  ALTER TABLE "REJECT_STRINGS" MODIFY ("REJECTID" NOT NULL ENABLE);
  ALTER TABLE "REJECT_STRINGS" MODIFY ("SHORTSTR" NOT NULL ENABLE);
  ALTER TABLE "REJECT_STRINGS" ADD CONSTRAINT "PRIMARY_24" PRIMARY KEY ("REJECTID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "ROLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ROLES" ADD CONSTRAINT "PRIMARY_29" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW_REJECT_STRING_MAP
--------------------------------------------------------

  ALTER TABLE "REVIEW_REJECT_STRING_MAP" MODIFY ("RRSID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_REJECT_STRING_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_REJECT_STRING_MAP" MODIFY ("RULEID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_REJECT_STRING_MAP" MODIFY ("REJECTID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_REJECT_STRING_MAP" ADD CONSTRAINT "PRIMARY_26" PRIMARY KEY ("RRSID")
  USING INDEX  ENABLE;
  ALTER TABLE "REVIEW_REJECT_STRING_MAP" ADD CONSTRAINT "INDEX2" UNIQUE ("ASSETID", "RULEID", "REJECTID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table STIG_ASSET_MAP
--------------------------------------------------------

  ALTER TABLE "STIG_ASSET_MAP" MODIFY ("SAID" NOT NULL ENABLE);
  ALTER TABLE "STIG_ASSET_MAP" MODIFY ("STIGID" NOT NULL ENABLE);
  ALTER TABLE "STIG_ASSET_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "STIG_ASSET_MAP" MODIFY ("DISABLEIMPORTS" NOT NULL ENABLE);
  ALTER TABLE "STIG_ASSET_MAP" ADD CONSTRAINT "PRIMARY_38" PRIMARY KEY ("SAID")
  USING INDEX  ENABLE;
  ALTER TABLE "STIG_ASSET_MAP" ADD CONSTRAINT "INDEX_2_3_C" UNIQUE ("STIGID", "ASSETID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW_ARTIFACT_MAP
--------------------------------------------------------

  ALTER TABLE "REVIEW_ARTIFACT_MAP" MODIFY ("RAID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_ARTIFACT_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_ARTIFACT_MAP" MODIFY ("RULEID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_ARTIFACT_MAP" MODIFY ("ARTID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_ARTIFACT_MAP" ADD CONSTRAINT "PRIMARY_25" PRIMARY KEY ("RAID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTIFACTS
--------------------------------------------------------

  ALTER TABLE "ARTIFACTS" MODIFY ("ARTID" NOT NULL ENABLE);
  ALTER TABLE "ARTIFACTS" MODIFY ("SHA1" NOT NULL ENABLE);
  ALTER TABLE "ARTIFACTS" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "ARTIFACTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "ARTIFACTS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "ARTIFACTS" MODIFY ("TS" NOT NULL ENABLE);
  ALTER TABLE "ARTIFACTS" MODIFY ("DEPT" NOT NULL ENABLE);
  ALTER TABLE "ARTIFACTS" ADD CONSTRAINT "PRIMARY_6" PRIMARY KEY ("ARTID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table PACKAGES
--------------------------------------------------------

  ALTER TABLE "PACKAGES" MODIFY ("PACKAGEID" NOT NULL ENABLE);
  ALTER TABLE "PACKAGES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PACKAGES" ADD CONSTRAINT "PRIMARY_22" PRIMARY KEY ("PACKAGEID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSETS
--------------------------------------------------------

  ALTER TABLE "ASSETS" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "ASSETS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ASSETS" MODIFY ("PROFILE" NOT NULL ENABLE);
  ALTER TABLE "ASSETS" ADD CONSTRAINT "PRIMARY_9" PRIMARY KEY ("ASSETID")
  USING INDEX  ENABLE;
  ALTER TABLE "ASSETS" ADD CONSTRAINT "INDEX_NAME" UNIQUE ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "ASSETS" ADD CONSTRAINT "ASSETS_CHK_IP_NN" CHECK ((IP IS NOT NULL AND NONNETWORK=0) OR (IP IS NULL AND NONNETWORK=1)) ENABLE;
  ALTER TABLE "ASSETS" ADD CONSTRAINT "ASSETS_CHK_NN_SE" CHECK ((NONNETWORK = 0 and SCANEXEMPT in (0,1)) OR (NONNETWORK=1 AND SCANEXEMPT=1)) ENABLE;
--------------------------------------------------------
--  Constraints for Table POAM_RAR_ENTRIES
--------------------------------------------------------

  ALTER TABLE "POAM_RAR_ENTRIES" MODIFY ("PREID" NOT NULL ENABLE);
  ALTER TABLE "POAM_RAR_ENTRIES" MODIFY ("PACKAGEID" NOT NULL ENABLE);
  ALTER TABLE "POAM_RAR_ENTRIES" MODIFY ("SOURCEID" NOT NULL ENABLE);
  ALTER TABLE "POAM_RAR_ENTRIES" ADD CONSTRAINT "PRIMARY_23" PRIMARY KEY ("PREID")
  USING INDEX  ENABLE;
  ALTER TABLE "POAM_RAR_ENTRIES" ADD CONSTRAINT "PACKAGEID_RULEID" UNIQUE ("PACKAGEID", "SOURCEID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUSES
--------------------------------------------------------

  ALTER TABLE "STATUSES" MODIFY ("STATUSID" NOT NULL ENABLE);
  ALTER TABLE "STATUSES" MODIFY ("STATUSSTR" NOT NULL ENABLE);
  ALTER TABLE "STATUSES" ADD CONSTRAINT "PRIMARY_32" PRIMARY KEY ("STATUSID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_DATA
--------------------------------------------------------

  ALTER TABLE "USER_DATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USER_DATA" ADD CONSTRAINT "PRIMARY_35" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "USER_DATA" ADD CONSTRAINT "INDEX_CN" UNIQUE ("CN")
  USING INDEX  ENABLE;
  ALTER TABLE "USER_DATA" ADD CONSTRAINT "INDEX_3_C" UNIQUE ("NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_STIG_ASSET_MAP
--------------------------------------------------------

  ALTER TABLE "USER_STIG_ASSET_MAP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USER_STIG_ASSET_MAP" ADD CONSTRAINT "PRIMARY_3" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "USER_STIG_ASSET_MAP" ADD CONSTRAINT "INDEX_2_1_C" UNIQUE ("USERID", "SAID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEWS
--------------------------------------------------------

  ALTER TABLE "REVIEWS" ADD CONSTRAINT "FK_REVIEWS_1" FOREIGN KEY ("ASSETID")
	  REFERENCES "ASSETS" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSET_PACKAGE_MAP
--------------------------------------------------------

  ALTER TABLE "ASSET_PACKAGE_MAP" ADD CONSTRAINT "FK_ASSET_PACKAGE_MAP_1" FOREIGN KEY ("PACKAGEID")
	  REFERENCES "PACKAGES" ("PACKAGEID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ASSET_PACKAGE_MAP" ADD CONSTRAINT "FK_ASSET_PACKAGE_MAP_2" FOREIGN KEY ("ASSETID")
	  REFERENCES "ASSETS" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATS_ASSET_STIG
--------------------------------------------------------

  ALTER TABLE "STATS_ASSET_STIG" ADD CONSTRAINT "FK_STATS_ASSET_STIG_1" FOREIGN KEY ("ASSETID")
	  REFERENCES "ASSETS" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STIG_ASSET_MAP
--------------------------------------------------------

  ALTER TABLE "STIG_ASSET_MAP" ADD CONSTRAINT "FK_STIG_ASSET_MAP_1" FOREIGN KEY ("ASSETID")
	  REFERENCES "ASSETS" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW_ARTIFACT_MAP
--------------------------------------------------------

  ALTER TABLE "REVIEW_ARTIFACT_MAP" ADD CONSTRAINT "FK_REVIEW_ARTIFACT_MAP_1" FOREIGN KEY ("ARTID")
	  REFERENCES "ARTIFACTS" ("ARTID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_STIG_ASSET_MAP
--------------------------------------------------------

  ALTER TABLE "USER_STIG_ASSET_MAP" ADD CONSTRAINT "FK_USER_STIG_ASSET_MAP_1" FOREIGN KEY ("USERID")
	  REFERENCES "USER_DATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "USER_STIG_ASSET_MAP" ADD CONSTRAINT "FK_USER_STIG_ASSET_MAP_2" FOREIGN KEY ("SAID")
	  REFERENCES "STIG_ASSET_MAP" ("SAID") ON DELETE CASCADE ENABLE;
