SET ECHO ON
SET VERIFY ON
SET FEEDBACK OFF
CLEAR SCREEN
set serveroutput on

set define on;
connect sys/&&sys_pw&&our_service as sysdba;
alter session set container=&&container_name;

-- PROMPT Creating Role &&iacontrols_role ...
-- CREATE ROLE &&iacontrols_role ;

 
PROMPT Create user iacontrols
CREATE USER iacontrols IDENTIFIED BY &&iacontrols_password DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SYNONYM, UNLIMITED TABLESPACE TO iacontrols;

-- PROMPT Drop Emulation user
-- drop user Emulation cascade;

-- prompt connecting to iacontrols
-- connect iacontrols/&&iacontrols_password@&&container_name;

--------------------------------------------------------
--  DDL for Table CCI
--------------------------------------------------------

  CREATE TABLE "IACONTROLS"."CCI" 
   (	"CCI" VARCHAR2(20 BYTE), 
	"CCINUM" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"PUBDATE" DATE, 
	"CONTRIBUTOR" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"IMPLEMENTATION" VARCHAR2(4000 BYTE), 
	"APACRONYM" VARCHAR2(20 BYTE), 
	"ASSESSMENTPROC" VARCHAR2(32000 BYTE), 
	"DEFINITION" VARCHAR2(32000 BYTE)
   ) ;
  GRANT ALTER ON "IACONTROLS"."CCI" TO &&iacontrols_role;
  GRANT DELETE ON "IACONTROLS"."CCI" TO &&iacontrols_role;
  GRANT INSERT ON "IACONTROLS"."CCI" TO &&iacontrols_role;
  GRANT SELECT ON "IACONTROLS"."CCI" TO &&iacontrols_role;
  GRANT UPDATE ON "IACONTROLS"."CCI" TO &&iacontrols_role;
  GRANT READ ON "IACONTROLS"."CCI" TO &&iacontrols_role;
  GRANT ON COMMIT REFRESH ON "IACONTROLS"."CCI" TO &&iacontrols_role;
  GRANT QUERY REWRITE ON "IACONTROLS"."CCI" TO &&iacontrols_role;
  GRANT DEBUG ON "IACONTROLS"."CCI" TO &&iacontrols_role;
  GRANT FLASHBACK ON "IACONTROLS"."CCI" TO &&iacontrols_role;
--------------------------------------------------------
--  DDL for Table CCI_CONTROL_MAP
--------------------------------------------------------

  CREATE TABLE "IACONTROLS"."CCI_CONTROL_MAP" 
   (	"CCI" VARCHAR2(20 BYTE), 
	"SOURCE" VARCHAR2(255 BYTE), 
	"REV" VARCHAR2(255 BYTE), 
	"CONTROL" VARCHAR2(20 BYTE), 
	"TEXTREF" VARCHAR2(40 BYTE)
   ) ;
  GRANT ALTER ON "IACONTROLS"."CCI_CONTROL_MAP" TO &&iacontrols_role;
  GRANT DELETE ON "IACONTROLS"."CCI_CONTROL_MAP" TO &&iacontrols_role;
  GRANT INSERT ON "IACONTROLS"."CCI_CONTROL_MAP" TO &&iacontrols_role;
  GRANT SELECT ON "IACONTROLS"."CCI_CONTROL_MAP" TO &&iacontrols_role;
  GRANT UPDATE ON "IACONTROLS"."CCI_CONTROL_MAP" TO &&iacontrols_role;
  GRANT READ ON "IACONTROLS"."CCI_CONTROL_MAP" TO &&iacontrols_role;
  GRANT ON COMMIT REFRESH ON "IACONTROLS"."CCI_CONTROL_MAP" TO &&iacontrols_role;
  GRANT QUERY REWRITE ON "IACONTROLS"."CCI_CONTROL_MAP" TO &&iacontrols_role;
  GRANT DEBUG ON "IACONTROLS"."CCI_CONTROL_MAP" TO &&iacontrols_role;
  GRANT FLASHBACK ON "IACONTROLS"."CCI_CONTROL_MAP" TO &&iacontrols_role;
--------------------------------------------------------
--  DDL for Table CONTROLS
--------------------------------------------------------

  CREATE TABLE "IACONTROLS"."CONTROLS" 
   (	"CONTROLNUMBER" CHAR(6 CHAR), 
	"CONTROLNAME" VARCHAR2(255 CHAR), 
	"SUBJECTAREA" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(32766 CHAR), 
	"TVC" VARCHAR2(32766 CHAR), 
	"GENIMPGUIDANCE" VARCHAR2(32766 CHAR), 
	"SYSGUIDANCERESOURCES" VARCHAR2(32766 CHAR), 
	"IMPACTCODE" VARCHAR2(4000 CHAR)
   ) ;
  GRANT ALTER ON "IACONTROLS"."CONTROLS" TO &&iacontrols_role;
  GRANT DELETE ON "IACONTROLS"."CONTROLS" TO &&iacontrols_role;
  GRANT INSERT ON "IACONTROLS"."CONTROLS" TO &&iacontrols_role;
  GRANT SELECT ON "IACONTROLS"."CONTROLS" TO &&iacontrols_role;
  GRANT UPDATE ON "IACONTROLS"."CONTROLS" TO &&iacontrols_role;
  GRANT READ ON "IACONTROLS"."CONTROLS" TO &&iacontrols_role;
  GRANT ON COMMIT REFRESH ON "IACONTROLS"."CONTROLS" TO &&iacontrols_role;
  GRANT QUERY REWRITE ON "IACONTROLS"."CONTROLS" TO &&iacontrols_role;
  GRANT DEBUG ON "IACONTROLS"."CONTROLS" TO &&iacontrols_role;
  GRANT FLASHBACK ON "IACONTROLS"."CONTROLS" TO &&iacontrols_role;
--------------------------------------------------------
--  DDL for Table CONTROL_MAC_MAP
--------------------------------------------------------

  CREATE TABLE "IACONTROLS"."CONTROL_MAC_MAP" 
   (	"CMID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CONTROLNUMBER" CHAR(6 CHAR) DEFAULT '0', 
	"MACCLID" NUMBER(10,0) DEFAULT '0'
   ) ;
  GRANT ALTER ON "IACONTROLS"."CONTROL_MAC_MAP" TO &&iacontrols_role;
  GRANT DELETE ON "IACONTROLS"."CONTROL_MAC_MAP" TO &&iacontrols_role;
  GRANT INSERT ON "IACONTROLS"."CONTROL_MAC_MAP" TO &&iacontrols_role;
  GRANT SELECT ON "IACONTROLS"."CONTROL_MAC_MAP" TO &&iacontrols_role;
  GRANT UPDATE ON "IACONTROLS"."CONTROL_MAC_MAP" TO &&iacontrols_role;
  GRANT READ ON "IACONTROLS"."CONTROL_MAC_MAP" TO &&iacontrols_role;
  GRANT ON COMMIT REFRESH ON "IACONTROLS"."CONTROL_MAC_MAP" TO &&iacontrols_role;
  GRANT QUERY REWRITE ON "IACONTROLS"."CONTROL_MAC_MAP" TO &&iacontrols_role;
  GRANT DEBUG ON "IACONTROLS"."CONTROL_MAC_MAP" TO &&iacontrols_role;
  GRANT FLASHBACK ON "IACONTROLS"."CONTROL_MAC_MAP" TO &&iacontrols_role;
--------------------------------------------------------
--  DDL for Table CONTROL_PROC_MAP
--------------------------------------------------------

  CREATE TABLE "IACONTROLS"."CONTROL_PROC_MAP" 
   (	"CPID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CONTROLNUMBER" CHAR(6 CHAR), 
	"VALPROCNUM" VARCHAR2(50 CHAR)
   ) ;
  GRANT ALTER ON "IACONTROLS"."CONTROL_PROC_MAP" TO &&iacontrols_role;
  GRANT DELETE ON "IACONTROLS"."CONTROL_PROC_MAP" TO &&iacontrols_role;
  GRANT INSERT ON "IACONTROLS"."CONTROL_PROC_MAP" TO &&iacontrols_role;
  GRANT SELECT ON "IACONTROLS"."CONTROL_PROC_MAP" TO &&iacontrols_role;
  GRANT UPDATE ON "IACONTROLS"."CONTROL_PROC_MAP" TO &&iacontrols_role;
  GRANT READ ON "IACONTROLS"."CONTROL_PROC_MAP" TO &&iacontrols_role;
  GRANT ON COMMIT REFRESH ON "IACONTROLS"."CONTROL_PROC_MAP" TO &&iacontrols_role;
  GRANT QUERY REWRITE ON "IACONTROLS"."CONTROL_PROC_MAP" TO &&iacontrols_role;
  GRANT DEBUG ON "IACONTROLS"."CONTROL_PROC_MAP" TO &&iacontrols_role;
  GRANT FLASHBACK ON "IACONTROLS"."CONTROL_PROC_MAP" TO &&iacontrols_role;
--------------------------------------------------------
--  DDL for Table MAC_CL
--------------------------------------------------------

  CREATE TABLE "IACONTROLS"."MAC_CL" 
   (	"MACCLID" NUMBER(10,0), 
	"LONGNAME" VARCHAR2(50 CHAR), 
	"SHORTNAME" VARCHAR2(50 CHAR), 
	"PROFILENAME" VARCHAR2(50 CHAR)
   ) ;
  GRANT ALTER ON "IACONTROLS"."MAC_CL" TO &&iacontrols_role;
  GRANT DELETE ON "IACONTROLS"."MAC_CL" TO &&iacontrols_role;
  GRANT INSERT ON "IACONTROLS"."MAC_CL" TO &&iacontrols_role;
  GRANT SELECT ON "IACONTROLS"."MAC_CL" TO &&iacontrols_role;
  GRANT UPDATE ON "IACONTROLS"."MAC_CL" TO &&iacontrols_role;
  GRANT READ ON "IACONTROLS"."MAC_CL" TO &&iacontrols_role;
  GRANT ON COMMIT REFRESH ON "IACONTROLS"."MAC_CL" TO &&iacontrols_role;
  GRANT QUERY REWRITE ON "IACONTROLS"."MAC_CL" TO &&iacontrols_role;
  GRANT DEBUG ON "IACONTROLS"."MAC_CL" TO &&iacontrols_role;
  GRANT FLASHBACK ON "IACONTROLS"."MAC_CL" TO &&iacontrols_role;
--------------------------------------------------------
--  DDL for Table PROCEDURES
--------------------------------------------------------

  CREATE TABLE "IACONTROLS"."PROCEDURES" 
   (	"VALPROCNUM" VARCHAR2(50 CHAR), 
	"PROCNAME" VARCHAR2(255 CHAR), 
	"PROCOBJ" VARCHAR2(32766 CHAR), 
	"PROCPREP" VARCHAR2(32766 CHAR), 
	"PROCSCRIPT" VARCHAR2(32766 CHAR), 
	"EXPECTEDRESULTS" VARCHAR2(32766 CHAR)
   ) ;
  GRANT ALTER ON "IACONTROLS"."PROCEDURES" TO &&iacontrols_role;
  GRANT DELETE ON "IACONTROLS"."PROCEDURES" TO &&iacontrols_role;
  GRANT INSERT ON "IACONTROLS"."PROCEDURES" TO &&iacontrols_role;
  GRANT SELECT ON "IACONTROLS"."PROCEDURES" TO &&iacontrols_role;
  GRANT UPDATE ON "IACONTROLS"."PROCEDURES" TO &&iacontrols_role;
  GRANT READ ON "IACONTROLS"."PROCEDURES" TO &&iacontrols_role;
  GRANT ON COMMIT REFRESH ON "IACONTROLS"."PROCEDURES" TO &&iacontrols_role;
  GRANT QUERY REWRITE ON "IACONTROLS"."PROCEDURES" TO &&iacontrols_role;
  GRANT DEBUG ON "IACONTROLS"."PROCEDURES" TO &&iacontrols_role;
  GRANT FLASHBACK ON "IACONTROLS"."PROCEDURES" TO &&iacontrols_role;
--------------------------------------------------------
--  DDL for Index PRIMARY_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IACONTROLS"."PRIMARY_1" ON "IACONTROLS"."CONTROL_PROC_MAP" ("CPID") 
  ;
--------------------------------------------------------
--  DDL for Index CCI_CONTROL_MAP_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IACONTROLS"."CCI_CONTROL_MAP_INDEX1" ON "IACONTROLS"."CCI_CONTROL_MAP" ("CCI", "REV", "CONTROL") 
  ;
--------------------------------------------------------
--  DDL for Index CCI_CONTROL_MAP_INDEX2
--------------------------------------------------------

  CREATE INDEX "IACONTROLS"."CCI_CONTROL_MAP_INDEX2" ON "IACONTROLS"."CCI_CONTROL_MAP" ("CONTROL", "TEXTREF") 
  ;
--------------------------------------------------------
--  DDL for Index CONTROLNUMBER_MACCLID
--------------------------------------------------------

  CREATE UNIQUE INDEX "IACONTROLS"."CONTROLNUMBER_MACCLID" ON "IACONTROLS"."CONTROL_MAC_MAP" ("CONTROLNUMBER", "MACCLID") 
  ;
--------------------------------------------------------
--  DDL for Index CCI_MAP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IACONTROLS"."CCI_MAP_PK" ON "IACONTROLS"."CCI" ("CCI") 
  ;
--------------------------------------------------------
--  DDL for Index CCI_MAP_INDEX_APACRONYM
--------------------------------------------------------

  CREATE INDEX "IACONTROLS"."CCI_MAP_INDEX_APACRONYM" ON "IACONTROLS"."CCI" ("APACRONYM") 
  ;
--------------------------------------------------------
--  DDL for Index CCI_MAP_INDEX_CCINUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "IACONTROLS"."CCI_MAP_INDEX_CCINUM" ON "IACONTROLS"."CCI" ("CCINUM") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_3
--------------------------------------------------------

  CREATE UNIQUE INDEX "IACONTROLS"."PRIMARY_3" ON "IACONTROLS"."MAC_CL" ("MACCLID") 
  ;
--------------------------------------------------------
--  DDL for Index CONTROLNUMBER_VALPROCNUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "IACONTROLS"."CONTROLNUMBER_VALPROCNUM" ON "IACONTROLS"."CONTROL_PROC_MAP" ("CONTROLNUMBER", "VALPROCNUM") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY
--------------------------------------------------------

  CREATE UNIQUE INDEX "IACONTROLS"."PRIMARY" ON "IACONTROLS"."CONTROL_MAC_MAP" ("CMID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_4
--------------------------------------------------------

  CREATE UNIQUE INDEX "IACONTROLS"."PRIMARY_4" ON "IACONTROLS"."CONTROLS" ("CONTROLNUMBER") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IACONTROLS"."PRIMARY_2" ON "IACONTROLS"."PROCEDURES" ("VALPROCNUM") 
  ;
--------------------------------------------------------
--  DDL for Trigger CONTROLS_IMPACTCODE_ETRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "IACONTROLS"."CONTROLS_IMPACTCODE_ETRG" 
BEFORE INSERT OR UPDATE ON iacontrols.controls
FOR EACH ROW
DECLARE
  v_val controls.impactCode%TYPE;
  v_test controls.impactCode%TYPE;
BEGIN
  v_val := null;
  v_test := TRIM(:new.impactCode);
  if v_test = '1' OR v_test = 'High' THEN 
  v_val := 'High';
  elsif v_test = '2' OR v_test = 'Medium' THEN 
  v_val := 'Medium';
  elsif v_test = '3' OR v_test = 'Low' THEN 
  v_val := 'Low';
  end if;  :new.impactCode := v_val;
END;

/
ALTER TRIGGER "IACONTROLS"."CONTROLS_IMPACTCODE_ETRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTROL_MAC_MAP_CMID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "IACONTROLS"."CONTROL_MAC_MAP_CMID_TRG" AFTER INSERT ON iacontrols.control_mac_map
FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
BEGIN
  v_newVal := :new.cmId;
  --used to emulate LAST_INSERT_ID()
  --mysql_utilities.identity := v_newVal; 
END;


/
ALTER TRIGGER "IACONTROLS"."CONTROL_MAC_MAP_CMID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTROL_PROC_MAP_CPID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "IACONTROLS"."CONTROL_PROC_MAP_CPID_TRG" AFTER INSERT ON iacontrols.control_proc_map
FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
BEGIN
  v_newVal := :new.cpId;
  --used to emulate LAST_INSERT_ID()
  --mysql_utilities.identity := v_newVal; 
END;


/
ALTER TRIGGER "IACONTROLS"."CONTROL_PROC_MAP_CPID_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CCI
--------------------------------------------------------

  ALTER TABLE "IACONTROLS"."CCI" ADD CONSTRAINT "CCI_MAP_PK" PRIMARY KEY ("CCI")
  USING INDEX  ENABLE;
  ALTER TABLE "IACONTROLS"."CCI" MODIFY ("CCI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAC_CL
--------------------------------------------------------

  ALTER TABLE "IACONTROLS"."MAC_CL" MODIFY ("MACCLID" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."MAC_CL" MODIFY ("LONGNAME" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."MAC_CL" MODIFY ("SHORTNAME" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."MAC_CL" MODIFY ("PROFILENAME" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."MAC_CL" ADD CONSTRAINT "PRIMARY_3" PRIMARY KEY ("MACCLID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROCEDURES
--------------------------------------------------------

  ALTER TABLE "IACONTROLS"."PROCEDURES" MODIFY ("VALPROCNUM" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."PROCEDURES" ADD CONSTRAINT "PRIMARY_2" PRIMARY KEY ("VALPROCNUM")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CCI_CONTROL_MAP
--------------------------------------------------------

  ALTER TABLE "IACONTROLS"."CCI_CONTROL_MAP" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."CCI_CONTROL_MAP" MODIFY ("CCI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTROL_MAC_MAP
--------------------------------------------------------

  -- ALTER TABLE "IACONTROLS"."CONTROL_MAC_MAP" MODIFY ("CMID" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."CONTROL_MAC_MAP" MODIFY ("CONTROLNUMBER" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."CONTROL_MAC_MAP" MODIFY ("MACCLID" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."CONTROL_MAC_MAP" ADD CONSTRAINT "PRIMARY" PRIMARY KEY ("CMID")
  USING INDEX  ENABLE;
  ALTER TABLE "IACONTROLS"."CONTROL_MAC_MAP" ADD CONSTRAINT "CONTROLNUMBER_MACCLID" UNIQUE ("CONTROLNUMBER", "MACCLID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTROL_PROC_MAP
--------------------------------------------------------

  -- ALTER TABLE "IACONTROLS"."CONTROL_PROC_MAP" MODIFY ("CPID" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."CONTROL_PROC_MAP" ADD CONSTRAINT "PRIMARY_1" PRIMARY KEY ("CPID")
  USING INDEX  ENABLE;
  ALTER TABLE "IACONTROLS"."CONTROL_PROC_MAP" ADD CONSTRAINT "CONTROLNUMBER_VALPROCNUM" UNIQUE ("CONTROLNUMBER", "VALPROCNUM")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTROLS
--------------------------------------------------------

  ALTER TABLE "IACONTROLS"."CONTROLS" MODIFY ("CONTROLNUMBER" NOT NULL ENABLE);
  ALTER TABLE "IACONTROLS"."CONTROLS" ADD CONSTRAINT "PRIMARY_4" PRIMARY KEY ("CONTROLNUMBER")
  USING INDEX  ENABLE;
