
SET ECHO ON
SET VERIFY ON
SET FEEDBACK OFF
CLEAR SCREEN
set serveroutput on

set define on;
connect sys/&&sys_pw&&our_service as sysdba;
alter session set container=&&container_name;

-- PROMPT Creating Role &&stigman_role ...
-- CREATE ROLE &&stigman_role ;

   
PROMPT Create user stigman
CREATE USER stigman IDENTIFIED BY &&stigman_password DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SYNONYM, UNLIMITED TABLESPACE TO stigman;


set define on
-- prompt connecting to stigman
-- connect stigman/&&stigman_password@&&container_name;

--------------------------------------------------------
--  DDL for Type PARAM_ARRAY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "STIGMAN"."PARAM_ARRAY" AS table OF VARCHAR2(100);

/
--------------------------------------------------------
--  DDL for Type STR_DIST_AGG_PARAM_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "STIGMAN"."STR_DIST_AGG_PARAM_TYPE" as object
(
  total varchar2(32767),
  delim varchar2(100),
  
  static function
       ODCIAggregateInitialize(sctx IN OUT str_dist_agg_param_type )
       return number,
  member function
       ODCIAggregateIterate(self IN OUT str_dist_agg_param_type ,
                            value IN param_array )
       return number,
  member function
       ODCIAggregateTerminate(self IN str_dist_agg_param_type,
                              returnValue OUT  varchar2,
                              flags IN number)
       return number,
  member function
       ODCIAggregateMerge(self IN OUT str_dist_agg_param_type,
                          ctx2 IN str_dist_agg_param_type)
       return number,
  member function
       ODCIAggregateDelete(self IN OUT str_dist_agg_param_type,
                           value in param_array)
       return number
)
/
CREATE OR REPLACE EDITIONABLE TYPE BODY "STIGMAN"."STR_DIST_AGG_PARAM_TYPE" 
is
--
static function ODCIAggregateInitialize(sctx IN OUT str_dist_agg_param_type)
return number
is
begin
   sctx := str_dist_agg_param_type( null, null );
   return ODCIConst.Success;
end;
--
member function ODCIAggregateIterate(self IN OUT str_dist_agg_param_type,
                                    value IN param_array )
return number
is
begin
   --Use chr(7) as an internal separator because, since
   --it is a pretty useless control character, it is unlikely
   --to be in the input data or cause any internal problems.
   self.total := self.total ||  value(1) || chr(7);

  --CSMIG: Set the output delimiter from the second item of value
   if (value.count = 2)
   then
      self.delim := value(2);
    else
      self.delim := ',';
   end if;
   return ODCIConst.Success;
end;
--
member function ODCIAggregateTerminate(self IN str_dist_agg_param_type,
                                      returnValue OUT varchar2,
                                      flags IN number)
return number
is
 type tab_dist is table of number index by varchar2(32767);
 t_dist tab_dist;
 v_point number := 0;
 v_str varchar2(32767);
 v_sep varchar2(1) := chr(7);
 v_ret varchar2(32767);
begin
 v_str := rtrim(ltrim(self.total,v_sep),v_sep);
 v_point := instr(v_str,v_sep);
 while nvl(v_point,0) != 0 loop
   t_dist(substr(v_str,1,v_point-1)) := 1;
   v_str := ltrim(substr(v_str,v_point),v_sep);
   v_point := instr(v_str,v_sep);
 end loop;
 t_dist(v_str) := 1;
 --
 v_str := t_dist.first;
 while v_str is not null loop
   if (v_ret is null) then
     v_ret := v_str;
   else 
    --CSMIG: Insert the delimiter into the concatenated string
     v_ret := v_ret || self.delim ||v_str;
   end if;
   v_str := t_dist.next(v_str);
 end loop;
 returnValue := v_ret;
 return ODCIConst.Success;
end;
--
member function ODCIAggregateDelete(self IN OUT str_dist_agg_param_type,
                                   value in param_array)
return number
is
 v_point number;
begin
 v_point := instr(self.total,value(1)||chr(7));
 if v_point > 0 then
   self.total := substr(self.total,1,v_point-1)||
                   substr(self.total, v_point+length(value(1))+1);
 end if;
 return ODCIConst.Success;
end;
--
member function ODCIAggregateMerge(self IN OUT str_dist_agg_param_type,
                                  ctx2 IN str_dist_agg_param_type)
return number
is
begin
 self.total := self.total ||chr(7)||ctx2.total;
 return ODCIConst.Success;
end;
end;

/
--------------------------------------------------------
--  DDL for Table ACTIONS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."ACTIONS" 
   (	"ACTIONID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ACTION" VARCHAR2(45 CHAR)
   ) ;
  GRANT INSERT ON "STIGMAN"."ACTIONS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."ACTIONS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."ACTIONS" TO &&stigman_role;
  GRANT DELETE ON "STIGMAN"."ACTIONS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table ACTIVITY
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."ACTIVITY" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_" VARCHAR2(45 CHAR), 
	"TIMESTAMP" DATE DEFAULT SYSDATE, 
	"USERNAME" VARCHAR2(45 CHAR), 
	"SCRIPT" CLOB, 
	"NAME" VARCHAR2(45 CHAR)
   ) ;

   COMMENT ON COLUMN "STIGMAN"."ACTIVITY"."USER_" IS 'ORIGINAL NAME:user';
  GRANT DELETE ON "STIGMAN"."ACTIVITY" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."ACTIVITY" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."ACTIVITY" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."ACTIVITY" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table ACTIVITY_DETAILS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."ACTIVITY_DETAILS" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ACTIVITYID" NUMBER(10,0), 
	"KEY" VARCHAR2(255 CHAR), 
	"VALUE" VARCHAR2(4000 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."ACTIVITY_DETAILS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."ACTIVITY_DETAILS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."ACTIVITY_DETAILS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."ACTIVITY_DETAILS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table ARTIFACTS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."ARTIFACTS" 
   (	"ARTID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SHA1" VARCHAR2(45 CHAR), 
	"FILENAME" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"USERID" NUMBER(10,0), 
	"TS" DATE DEFAULT SYSDATE, 
	"DEPT" VARCHAR2(45 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."ARTIFACTS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."ARTIFACTS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."ARTIFACTS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."ARTIFACTS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table ARTIFACT_BLOBS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."ARTIFACT_BLOBS" 
   (	"SHA1" VARCHAR2(45 CHAR), 
	"DATA" BLOB, 
	"TS" DATE DEFAULT SYSDATE, 
	"USERID" NUMBER(10,0)
   ) ;
  GRANT DELETE ON "STIGMAN"."ARTIFACT_BLOBS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."ARTIFACT_BLOBS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."ARTIFACT_BLOBS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."ARTIFACT_BLOBS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table ASSETS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."ASSETS" 
   (	"ASSETID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(45 CHAR), 
	"PROFILE" VARCHAR2(45 CHAR) DEFAULT 'MAC-3_Sensitive', 
	"DOMAIN" VARCHAR2(45 CHAR), 
	"IP" VARCHAR2(45 CHAR), 
	"DEPT" VARCHAR2(45 CHAR), 
	"NONNETWORK" CHAR(1 BYTE) DEFAULT 0, 
	"SCANEXEMPT" CHAR(1 BYTE) DEFAULT 0
   ) ;
  GRANT DELETE ON "STIGMAN"."ASSETS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."ASSETS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."ASSETS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."ASSETS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table ASSET_GROUPS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."ASSET_GROUPS" 
   (	"GROUPID" VARCHAR2(45 CHAR), 
	"GROUPNAME" VARCHAR2(45 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."ASSET_GROUPS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."ASSET_GROUPS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."ASSET_GROUPS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."ASSET_GROUPS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table ASSET_PACKAGE_MAP
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."ASSET_PACKAGE_MAP" 
   (	"APID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"PACKAGEID" NUMBER(10,0), 
	"SCANRESULTID" NUMBER(10,0)
   ) ;
  GRANT DELETE ON "STIGMAN"."ASSET_PACKAGE_MAP" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."ASSET_PACKAGE_MAP" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."ASSET_PACKAGE_MAP" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."ASSET_PACKAGE_MAP" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table AUDITS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."AUDITS" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TS" DATE DEFAULT SYSDATE, 
	"USERID" NUMBER(10,0), 
	"LOGTEXT" VARCHAR2(255 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."AUDITS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."AUDITS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."AUDITS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."AUDITS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table DOMAIN_DEPT_MAP
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."DOMAIN_DEPT_MAP" 
   (	"DDID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DOMAIN" VARCHAR2(45 CHAR), 
	"DEPT" VARCHAR2(45 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."DOMAIN_DEPT_MAP" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."DOMAIN_DEPT_MAP" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."DOMAIN_DEPT_MAP" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."DOMAIN_DEPT_MAP" TO &&stigman_role;

--------------------------------------------------------
--  DDL for Table IACONTROL_IMPACT_MAP
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."IACONTROL_IMPACT_MAP" 
   (	"IACONTROL" CHAR(6 CHAR), 
	"IMPACT" VARCHAR2(4000 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."IACONTROL_IMPACT_MAP" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."IACONTROL_IMPACT_MAP" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."IACONTROL_IMPACT_MAP" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."IACONTROL_IMPACT_MAP" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table IMPORTED_BLOBS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."IMPORTED_BLOBS" 
   (	"SHA1" VARCHAR2(255 CHAR), 
	"DATA" BLOB
   ) ;
  GRANT DELETE ON "STIGMAN"."IMPORTED_BLOBS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."IMPORTED_BLOBS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."IMPORTED_BLOBS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."IMPORTED_BLOBS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table IMPORTED_JOBS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."IMPORTED_JOBS" 
   (	"JOBID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STARTTIME" DATE, 
	"USERID" NUMBER(10,0), 
	"STIGMANID" VARCHAR2(45 CHAR), 
	"SOURCE" VARCHAR2(45 CHAR), 
	"ASSETID" NUMBER(10,0), 
	"STIGID" VARCHAR2(255 CHAR), 
	"PACKAGEID" NUMBER(10,0), 
	"FILENAME" VARCHAR2(256 CHAR), 
	"FILESIZE" NUMBER(10,0), 
	"MODIFIED" VARCHAR2(255 CHAR), 
	"FILEMD" VARCHAR2(50 CHAR), 
	"REPORTTEXT" VARCHAR2(32766 CHAR), 
	"ENDTIME" DATE
   ) ;
  GRANT DELETE ON "STIGMAN"."IMPORTED_JOBS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."IMPORTED_JOBS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."IMPORTED_JOBS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."IMPORTED_JOBS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table IMPORTED_RESULTS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."IMPORTED_RESULTS" 
   (	"IMPORTID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" NUMBER(10,0), 
	"USER_" VARCHAR2(50 CHAR), 
	"CN" VARCHAR2(50 CHAR), 
	"ASSETID" NUMBER(10,0), 
	"ASSET" VARCHAR2(50 CHAR), 
	"SUBMITTEDASSET" VARCHAR2(50 CHAR), 
	"STIGTITLE" VARCHAR2(255 CHAR), 
	"SUBMITTEDSTIGTITLE" VARCHAR2(255 CHAR), 
	"TIMESTAMP" DATE DEFAULT SYSDATE, 
	"SHA1" VARCHAR2(255 CHAR), 
	"FILENAME" VARCHAR2(1024 CHAR), 
	"DATA" BLOB, 
	"ACCEPTED" NUMBER(3,0), 
	"CHECKSSUBMITTED" NUMBER(10,0), 
	"CHECKSIMPORTED" NUMBER(10,0)
   ) ;

   COMMENT ON COLUMN "STIGMAN"."IMPORTED_RESULTS"."USER_" IS 'ORIGINAL NAME:user';
  GRANT DELETE ON "STIGMAN"."IMPORTED_RESULTS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."IMPORTED_RESULTS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."IMPORTED_RESULTS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."IMPORTED_RESULTS" TO &&stigman_role;

--------------------------------------------------------
--  DDL for Table PACKAGES
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."PACKAGES" 
   (	"PACKAGEID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(45 CHAR), 
	"BOUNDARYID" VARCHAR2(45 CHAR), 
	"EMASSID" VARCHAR2(45 CHAR), 
	"REQRAR" NUMBER(3,0), 
	"POCNAME" VARCHAR2(50 CHAR), 
	"POCEMAIL" VARCHAR2(50 CHAR), 
	"POCPHONE" VARCHAR2(50 CHAR), 
	"MACCLID" NUMBER(10,0), 
	"REPOSITORYID" NUMBER(10,0)
   ) ;
  GRANT DELETE ON "STIGMAN"."PACKAGES" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."PACKAGES" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."PACKAGES" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."PACKAGES" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table POAM_RAR_ENTRIES
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."POAM_RAR_ENTRIES" 
   (	"PREID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PACKAGEID" NUMBER(10,0), 
	"FINDINGTYPE" VARCHAR2(50 CHAR), 
	"SOURCEID" VARCHAR2(45 CHAR), 
	"IACONTROL" VARCHAR2(45 CHAR), 
	"STATUS" VARCHAR2(45 CHAR), 
	"POC" VARCHAR2(255 CHAR), 
	"RESOURCES" VARCHAR2(255 CHAR), 
	"COMPDATE" DATE, 
	"MILESTONE" VARCHAR2(32766 CHAR), 
	"POAMCOMMENT" VARCHAR2(32766 CHAR), 
	"LIKELIHOOD" VARCHAR2(50 CHAR), 
	"MITDESC" VARCHAR2(32766 CHAR), 
	"RESIDUALRISK" NUMBER(10,0), 
	"RECCORRACT" VARCHAR2(32766 CHAR), 
	"REMDESC" VARCHAR2(32766 CHAR), 
	"RARCOMMENT" VARCHAR2(32766 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."POAM_RAR_ENTRIES" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."POAM_RAR_ENTRIES" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."POAM_RAR_ENTRIES" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."POAM_RAR_ENTRIES" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table REJECT_STRINGS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."REJECT_STRINGS" 
   (	"REJECTID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SHORTSTR" VARCHAR2(45 CHAR), 
	"LONGSTR" VARCHAR2(32766 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."REJECT_STRINGS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."REJECT_STRINGS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."REJECT_STRINGS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."REJECT_STRINGS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table REVIEWS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."REVIEWS" 
   (	"REVIEWID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR), 
	"STATEID" NUMBER(10,0), 
	"USERID" NUMBER(10,0), 
	"STATECOMMENT" VARCHAR2(32766 CHAR), 
	"ACTIONID" NUMBER(10,0), 
	"ACTIONCOMMENT" VARCHAR2(32766 CHAR), 
	"REQDOC" NUMBER(3,0) DEFAULT '0', 
	"AUTOSTATE" NUMBER(3,0) DEFAULT '0', 
	"TS" DATE DEFAULT SYSDATE, 
	"REJECTTEXT" VARCHAR2(32766 CHAR), 
	"REJECTUSERID" NUMBER(10,0), 
	"STATUSID" NUMBER(10,0) DEFAULT '0'
   ) ;
  GRANT DELETE ON "STIGMAN"."REVIEWS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."REVIEWS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."REVIEWS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."REVIEWS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table REVIEWS_HISTORY
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."REVIEWS_HISTORY" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR), 
	"ACTIVITYTYPE" VARCHAR2(45 CHAR), 
	"COLUMNNAME" VARCHAR2(45 CHAR), 
	"OLDVALUE" VARCHAR2(32766 CHAR), 
	"NEWVALUE" VARCHAR2(32766 CHAR), 
	"USERID" NUMBER(10,0), 
	"TS" DATE DEFAULT SYSDATE
   ) ;
  GRANT DELETE ON "STIGMAN"."REVIEWS_HISTORY" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."REVIEWS_HISTORY" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."REVIEWS_HISTORY" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."REVIEWS_HISTORY" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table REVIEW_ARTIFACT_MAP
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."REVIEW_ARTIFACT_MAP" 
   (	"RAID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR), 
	"ARTID" NUMBER(10,0), 
	"USERID" NUMBER(10,0)
   ) ;
  GRANT DELETE ON "STIGMAN"."REVIEW_ARTIFACT_MAP" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."REVIEW_ARTIFACT_MAP" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."REVIEW_ARTIFACT_MAP" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."REVIEW_ARTIFACT_MAP" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table REVIEW_REJECT_STRING_MAP
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."REVIEW_REJECT_STRING_MAP" 
   (	"RRSID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR), 
	"REJECTID" NUMBER(10,0), 
	"USERID" NUMBER(10,0)
   ) ;
  GRANT DELETE ON "STIGMAN"."REVIEW_REJECT_STRING_MAP" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."REVIEW_REJECT_STRING_MAP" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."REVIEW_REJECT_STRING_MAP" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."REVIEW_REJECT_STRING_MAP" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."ROLES" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROLE" VARCHAR2(45 CHAR), 
	"ROLEDISPLAY" VARCHAR2(45 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."ROLES" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."ROLES" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."ROLES" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."ROLES" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table STATES
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."STATES" 
   (	"STATEID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STATE" VARCHAR2(45 CHAR), 
	"ABBR" VARCHAR2(3 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."STATES" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."STATES" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."STATES" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."STATES" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table STATS_ASSET_STIG
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."STATS_ASSET_STIG" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"STIGID" VARCHAR2(255 CHAR), 
	"MINTS" DATE, 
	"MAXTS" DATE, 
	"CHECKSMANUAL" NUMBER(10,0), 
	"CHECKSSCAP" NUMBER(10,0), 
	"INPROGRESSMANUAL" NUMBER(10,0), 
	"INPROGRESSSCAP" NUMBER(10,0), 
	"SUBMITTEDMANUAL" NUMBER(10,0), 
	"SUBMITTEDSCAP" NUMBER(10,0), 
	"REJECTEDMANUAL" NUMBER(10,0), 
	"REJECTEDSCAP" NUMBER(10,0), 
	"APPROVEDMANUAL" NUMBER(10,0), 
	"APPROVEDSCAP" NUMBER(10,0), 
	"CAT1COUNT" NUMBER(10,0), 
	"CAT2COUNT" NUMBER(10,0), 
	"CAT3COUNT" NUMBER(10,0)
   ) ;
  GRANT DELETE ON "STIGMAN"."STATS_ASSET_STIG" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."STATS_ASSET_STIG" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."STATS_ASSET_STIG" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."STATS_ASSET_STIG" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table STATUSES
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."STATUSES" 
   (	"STATUSID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STATUSSTR" VARCHAR2(45 CHAR)
   ) ;
  GRANT DELETE ON "STIGMAN"."STATUSES" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."STATUSES" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."STATUSES" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."STATUSES" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table STIGMAN_IDS
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."STIGMAN_IDS" 
   (	"GUID" VARCHAR2(45 CHAR), 
	"CN" VARCHAR2(45 CHAR), 
	"LASTUSE" NUMBER(10,0)
   ) ;
  GRANT DELETE ON "STIGMAN"."STIGMAN_IDS" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."STIGMAN_IDS" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."STIGMAN_IDS" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."STIGMAN_IDS" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table STIG_ASSET_MAP
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."STIG_ASSET_MAP" 
   (	"SAID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STIGID" VARCHAR2(255 CHAR), 
	"ASSETID" NUMBER(10,0), 
	"DISABLEIMPORTS" NUMBER(3,0) DEFAULT '0'
   ) ;
  GRANT DELETE ON "STIGMAN"."STIG_ASSET_MAP" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."STIG_ASSET_MAP" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."STIG_ASSET_MAP" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."STIG_ASSET_MAP" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table USER_ASSET_MAP
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."USER_ASSET_MAP" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" NUMBER(10,0), 
	"ASSETID" NUMBER(10,0)
   ) ;
  GRANT DELETE ON "STIGMAN"."USER_ASSET_MAP" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."USER_ASSET_MAP" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."USER_ASSET_MAP" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."USER_ASSET_MAP" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table USER_DATA
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."USER_DATA" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CN" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"DEPT" VARCHAR2(45 CHAR), 
	"ROLEID" NUMBER(10,0), 
	"CANADMIN" NUMBER(3,0) DEFAULT '0'
   ) ;
  GRANT DELETE ON "STIGMAN"."USER_DATA" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."USER_DATA" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."USER_DATA" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."USER_DATA" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table USER_ROLE_MAP
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."USER_ROLE_MAP" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" NUMBER(10,0), 
	"ROLEID" NUMBER(10,0)
   ) ;
  GRANT DELETE ON "STIGMAN"."USER_ROLE_MAP" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."USER_ROLE_MAP" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."USER_ROLE_MAP" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."USER_ROLE_MAP" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Table USER_STIG_ASSET_MAP
--------------------------------------------------------

  CREATE TABLE "STIGMAN"."USER_STIG_ASSET_MAP" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" NUMBER(10,0), 
	"SAID" NUMBER(10,0)
   ) ;
  GRANT DELETE ON "STIGMAN"."USER_STIG_ASSET_MAP" TO &&stigman_role;
  GRANT INSERT ON "STIGMAN"."USER_STIG_ASSET_MAP" TO &&stigman_role;
  GRANT SELECT ON "STIGMAN"."USER_STIG_ASSET_MAP" TO &&stigman_role;
  GRANT UPDATE ON "STIGMAN"."USER_STIG_ASSET_MAP" TO &&stigman_role;
--------------------------------------------------------
--  DDL for Index PRIMARY_13
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_13" ON "STIGMAN"."IACONTROL_IMPACT_MAP" ("IACONTROL") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_1_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."INDEX_2_1_1" ON "STIGMAN"."REVIEWS" ("ASSETID", "RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_2_C
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."INDEX_2_2_C" ON "STIGMAN"."STATS_ASSET_STIG" ("ASSETID", "STIGID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_1_C
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."INDEX_2_1_C" ON "STIGMAN"."USER_STIG_ASSET_MAP" ("USERID", "SAID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_1
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_1" ON "STIGMAN"."IMPORTED_RESULTS" ("IMPORTID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_25
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_25" ON "STIGMAN"."REVIEW_ARTIFACT_MAP" ("RAID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_36
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_36" ON "STIGMAN"."USER_ROLE_MAP" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_PROFILE
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_PROFILE" ON "STIGMAN"."ASSETS" ("PROFILE") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_23
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_23" ON "STIGMAN"."POAM_RAR_ENTRIES" ("PREID") 
  ;
--------------------------------------------------------
--  DDL for Index DISABLEIMPORTS
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."DISABLEIMPORTS" ON "STIGMAN"."STIG_ASSET_MAP" ("DISABLEIMPORTS") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3_38
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_3_38" ON "STIGMAN"."USER_ROLE_MAP" ("ROLEID", "USERID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3_2
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_3_2" ON "STIGMAN"."USER_STIG_ASSET_MAP" ("SAID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_37
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_37" ON "STIGMAN"."ACTIVITY" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_10
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_10" ON "STIGMAN"."AUDITS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_3_C
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."INDEX_2_3_C" ON "STIGMAN"."STIG_ASSET_MAP" ("STIGID", "ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3_C
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."INDEX_3_C" ON "STIGMAN"."USER_DATA" ("NAME") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_1
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_2_1" ON "STIGMAN"."REVIEW_ARTIFACT_MAP" ("ASSETID", "RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_11
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_11" ON "STIGMAN"."DOMAIN_DEPT_MAP" ("DDID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_15
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_15" ON "STIGMAN"."IMPORTED_JOBS" ("JOBID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_22
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_22" ON "STIGMAN"."PACKAGES" ("PACKAGEID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_35
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_35" ON "STIGMAN"."USER_DATA" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_SHA1
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_SHA1" ON "STIGMAN"."ARTIFACTS" ("SHA1") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_4
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_4" ON "STIGMAN"."REVIEWS" ("STATEID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_NONNETWORK
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_NONNETWORK" ON "STIGMAN"."ASSETS" ("NONNETWORK") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY" ON "STIGMAN"."ACTIONS" ("ACTIONID") 
  ;

--------------------------------------------------------
--  DDL for Index INDEX2
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."INDEX2" ON "STIGMAN"."REVIEW_REJECT_STRING_MAP" ("ASSETID", "RULEID", "REJECTID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_ACTIVITYTYPE
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_ACTIVITYTYPE" ON "STIGMAN"."REVIEWS_HISTORY" ("ACTIVITYTYPE") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_ASSETID
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_ASSETID" ON "STIGMAN"."REVIEWS_HISTORY" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_SCANEXEMPT
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_SCANEXEMPT" ON "STIGMAN"."ASSETS" ("SCANEXEMPT") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_30
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_30" ON "STIGMAN"."STATES" ("STATEID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_6
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_6" ON "STIGMAN"."ARTIFACTS" ("ARTID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_9
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_9" ON "STIGMAN"."ASSETS" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_27
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_27" ON "STIGMAN"."REVIEWS" ("REVIEWID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_29
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_29" ON "STIGMAN"."ROLES" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_COLUMNNAME
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_COLUMNNAME" ON "STIGMAN"."REVIEWS_HISTORY" ("COLUMNNAME") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_2" ON "STIGMAN"."USER_ROLE_MAP" ("USERID") 
  ;
--------------------------------------------------------
--  DDL for Index ASSET_PACKAGE_MAP_INDEX2
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."ASSET_PACKAGE_MAP_INDEX2" ON "STIGMAN"."ASSET_PACKAGE_MAP" ("SCANRESULTID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_DEPT
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_DEPT" ON "STIGMAN"."ASSETS" ("DEPT") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_38
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_38" ON "STIGMAN"."STIG_ASSET_MAP" ("SAID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_3
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_3" ON "STIGMAN"."USER_STIG_ASSET_MAP" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_RULEID
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_RULEID" ON "STIGMAN"."REVIEWS_HISTORY" ("RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index FK_STATS_ASSET_STIG_2
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."FK_STATS_ASSET_STIG_2" ON "STIGMAN"."STATS_ASSET_STIG" ("STIGID") 
  ;
--------------------------------------------------------
--  DDL for Index PACKAGEID_RULEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PACKAGEID_RULEID" ON "STIGMAN"."POAM_RAR_ENTRIES" ("PACKAGEID", "SOURCEID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_24
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_24" ON "STIGMAN"."REJECT_STRINGS" ("REJECTID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3_1
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_3_1" ON "STIGMAN"."ASSET_PACKAGE_MAP" ("PACKAGEID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3_3
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_3_3" ON "STIGMAN"."REVIEWS" ("RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_34
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_34" ON "STIGMAN"."USER_ASSET_MAP" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index FK_STIGASSETMAP_1
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."FK_STIGASSETMAP_1" ON "STIGMAN"."STIG_ASSET_MAP" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_8
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_8" ON "STIGMAN"."ASSET_PACKAGE_MAP" ("APID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."INDEX_NAME" ON "STIGMAN"."ASSETS" ("NAME") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_26
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_26" ON "STIGMAN"."REVIEW_REJECT_STRING_MAP" ("RRSID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_33
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_33" ON "STIGMAN"."STIGMAN_IDS" ("GUID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_CN
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."INDEX_CN" ON "STIGMAN"."USER_DATA" ("CN") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_3" ON "STIGMAN"."REVIEW_ARTIFACT_MAP" ("ARTID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_7
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_7" ON "STIGMAN"."ASSET_GROUPS" ("GROUPID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_31
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_31" ON "STIGMAN"."STATS_ASSET_STIG" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_2
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_2_2" ON "STIGMAN"."ASSET_PACKAGE_MAP" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index FINDINGTYPE
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."FINDINGTYPE" ON "STIGMAN"."POAM_RAR_ENTRIES" ("FINDINGTYPE") 
  ;
-------------------------------------------------
--  DDL for Index PRIMARY_4
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_4" ON "STIGMAN"."ACTIVITY_DETAILS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_14
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_14" ON "STIGMAN"."IMPORTED_BLOBS" ("SHA1") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_28
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_28" ON "STIGMAN"."REVIEWS_HISTORY" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_32
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_32" ON "STIGMAN"."STATUSES" ("STATUSID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_STATUSID
--------------------------------------------------------

  CREATE INDEX "STIGMAN"."INDEX_STATUSID" ON "STIGMAN"."REVIEWS" ("STATUSID") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_5
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."PRIMARY_5" ON "STIGMAN"."ARTIFACT_BLOBS" ("SHA1") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_38
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."INDEX_2_38" ON "STIGMAN"."USER_ASSET_MAP" ("USERID", "ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index ASSET_PACKAGE_MAP_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STIGMAN"."ASSET_PACKAGE_MAP_INDEX1" ON "STIGMAN"."ASSET_PACKAGE_MAP" ("PACKAGEID", "ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Trigger ASSETS_AUPD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STIGMAN"."ASSETS_AUPD" 
AFTER UPDATE OF IP,SCANEXEMPT ON stigman.ASSETS 
FOR EACH ROW 
BEGIN
  IF (
    (:NEW.ip is null
    AND :OLD.ip is not null)
    OR
    (:NEW.ip is not null AND 
    :OLD.ip is not null AND
    :NEW.ip != :OLD.ip)
    OR
    (:NEW.SCANEXEMPT != :OLD.SCANEXEMPT AND
    :NEW.SCANEXEMPT = 1)
  )
  THEN
    UPDATE stigman.ASSET_PACKAGE_MAP SET SCANRESULTID=NULL WHERE ASSETID=:NEW.assetId;
  END IF;
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
ALTER TRIGGER "STIGMAN"."ASSETS_AUPD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger IACONTROL_IMYCAXIZ_IMPACT_ETRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STIGMAN"."IACONTROL_IMYCAXIZ_IMPACT_ETRG" 
BEFORE INSERT OR UPDATE ON stigman.iacontrol_impact_map
FOR EACH ROW
DECLARE
  v_val iacontrol_impact_map.impact%TYPE;
  v_test iacontrol_impact_map.impact%TYPE;
BEGIN
  v_val := null;
  v_test := TRIM(:new.impact);
  if v_test = '1' OR v_test = 'High' THEN 
  v_val := 'High';
  elsif v_test = '2' OR v_test = 'Medium' THEN 
  v_val := 'Medium';
  elsif v_test = '3' OR v_test = 'Low' THEN 
  v_val := 'Low';
  end if;  :new.impact := v_val;
END;
/
ALTER TRIGGER "STIGMAN"."IACONTROL_IMYCAXIZ_IMPACT_ETRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PACKAGES_AUPD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STIGMAN"."PACKAGES_AUPD" 
AFTER UPDATE OF REPOSITORYID ON stigman.PACKAGES 
FOR EACH ROW 
BEGIN
  IF (
    :new.repositoryId is null or
    (:old.repositoryId is not null and :new.repositoryId != :old.repositoryId))
  THEN
    UPDATE stigman.ASSET_PACKAGE_MAP SET SCANRESULTID=NULL WHERE PACKAGEID = :new.packageId;
  END IF;
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
ALTER TRIGGER "STIGMAN"."PACKAGES_AUPD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REVIEWS_AINS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STIGMAN"."REVIEWS_AINS" 
AFTER INSERT ON stigman.REVIEWS
FOR EACH ROW

BEGIN
 	IF :NEW.stateId IS NOT NULL THEN
		INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,newValue,userId)
		VALUES (:NEW.assetId,:NEW.ruleId,'insert','stateId',:NEW.stateId,:NEW.userId);
	END IF;
	IF :NEW.stateComment IS NOT NULL THEN
		INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,newValue,userId)
		VALUES (:NEW.assetId,:NEW.ruleId,'insert','stateComment',:NEW.stateComment,:NEW.userId);
	END IF;
	IF :NEW.actionId IS NOT NULL THEN
		INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,newValue,userId)
		VALUES (:NEW.assetId,:NEW.ruleId,'insert','actionId',:NEW.actionId,:NEW.userId);
	END IF;
	IF :NEW.actionComment IS NOT NULL THEN
		INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,newValue,userId)
		VALUES (:NEW.assetId,:NEW.ruleId,'insert','actionComment',:NEW.actionComment,:NEW.userId);
	END IF;
END;
/
ALTER TRIGGER "STIGMAN"."REVIEWS_AINS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REVIEWS_AUPD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STIGMAN"."REVIEWS_AUPD" 
AFTER UPDATE ON stigman.REVIEWS
FOR EACH ROW
BEGIN
        IF (NVL(:NEW.stateId,0) != NVL(:OLD.stateId,0)) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','stateId',:OLD.stateId,:NEW.stateId,:NEW.userId);
        END IF;

        IF (NVL(:NEW.statusId,0) != NVL(:OLD.statusId,0)) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','statusId',:OLD.statusId,:NEW.statusId,:NEW.userId);
        END IF;

        IF (NVL(:NEW.stateComment,'0') != NVL(:OLD.stateComment,'0')) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','stateComment',:OLD.stateComment,:NEW.stateComment,:NEW.userId);
        END IF;

        IF (NVL(:NEW.actionId,0) != NVL(:OLD.actionId,0)) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','actionId',:OLD.actionId,:NEW.actionId,:NEW.userId);
        END IF;

        IF (NVL(:NEW.actionComment,'0') != NVL(:OLD.actionComment,'0')) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','actionComment',:OLD.actionComment,:NEW.actionComment,:NEW.userId);
        END IF;

        IF (NVL(:NEW.rejectText,'0') != NVL(:OLD.rejectText,'0')) THEN
                INSERT INTO reviews_history (assetId,ruleId,activityType,columnName,oldValue,newValue,userId)
                VALUES (:NEW.assetId,:NEW.ruleId,'update','rejectText',:OLD.rejectText,:NEW.rejectText,:NEW.userId);
        END IF;        
END;
/
ALTER TRIGGER "STIGMAN"."REVIEWS_AUPD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REVIEWS_BUPD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STIGMAN"."REVIEWS_BUPD" 
BEFORE UPDATE ON stigman.REVIEWS 
FOR EACH ROW
BEGIN
	IF (:NEW.stateId = 2 OR :NEW.stateId = 3) THEN
		:NEW.actionId := NULL;
		:NEW.actionComment := NULL;
	END IF;
	:NEW.ts := SYSDATE;
END;
/
ALTER TRIGGER "STIGMAN"."REVIEWS_BUPD" ENABLE;
--------------------------------------------------------
--  DDL for Function FROM_UNIXTIME
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "STIGMAN"."FROM_UNIXTIME" ( p_unix_ts IN NUMBER )
  RETURN TIMESTAMP
IS
  l_ts TIMESTAMP;
BEGIN
  l_ts := TIMESTAMP '1970-01-01 00:00:00' + p_unix_ts/60/60/24;
  RETURN l_ts;
END;

/
--------------------------------------------------------
--  DDL for Function FROM_UNIXTIME_TZ
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "STIGMAN"."FROM_UNIXTIME_TZ" ( p_unix_ts IN NUMBER , p_tz IN VARCHAR2)
  RETURN TIMESTAMP WITH TIME ZONE
IS
  l_tstz TIMESTAMP WITH TIME ZONE;
BEGIN
  l_tstz := FROM_TZ(TIMESTAMP '1970-01-01 00:00:00' + p_unix_ts/60/60/24,p_tz);
  RETURN l_tstz;
END;

/
--------------------------------------------------------
--  DDL for Function STRDAGG_PARAM
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "STIGMAN"."STRDAGG_PARAM" (input param_array )
 RETURN varchar2
 PARALLEL_ENABLE AGGREGATE USING str_dist_agg_param_type;

/
--------------------------------------------------------
--  Constraints for Table IMPORTED_BLOBS
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."IMPORTED_BLOBS" MODIFY ("SHA1" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."IMPORTED_BLOBS" ADD CONSTRAINT "PRIMARY_14" PRIMARY KEY ("SHA1")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW_REJECT_STRING_MAP
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."REVIEW_REJECT_STRING_MAP" MODIFY ("RRSID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEW_REJECT_STRING_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEW_REJECT_STRING_MAP" MODIFY ("RULEID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEW_REJECT_STRING_MAP" MODIFY ("REJECTID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEW_REJECT_STRING_MAP" ADD CONSTRAINT "PRIMARY_26" PRIMARY KEY ("RRSID")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."REVIEW_REJECT_STRING_MAP" ADD CONSTRAINT "INDEX2" UNIQUE ("ASSETID", "RULEID", "REJECTID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."ROLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ROLES" ADD CONSTRAINT "PRIMARY_29" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATES
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."STATES" MODIFY ("STATEID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."STATES" ADD CONSTRAINT "PRIMARY_30" PRIMARY KEY ("STATEID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_ROLE_MAP
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."USER_ROLE_MAP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."USER_ROLE_MAP" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."USER_ROLE_MAP" MODIFY ("ROLEID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."USER_ROLE_MAP" ADD CONSTRAINT "PRIMARY_36" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOMAIN_DEPT_MAP
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."DOMAIN_DEPT_MAP" MODIFY ("DDID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."DOMAIN_DEPT_MAP" ADD CONSTRAINT "PRIMARY_11" PRIMARY KEY ("DDID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEWS
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."REVIEWS" MODIFY ("REVIEWID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEWS" MODIFY ("TS" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEWS" MODIFY ("STATUSID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEWS" ADD CONSTRAINT "INDEX_2_1_1" UNIQUE ("ASSETID", "RULEID")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."REVIEWS" ADD CONSTRAINT "PRIMARY_27" PRIMARY KEY ("REVIEWID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSET_PACKAGE_MAP
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."ASSET_PACKAGE_MAP" MODIFY ("APID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ASSET_PACKAGE_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ASSET_PACKAGE_MAP" MODIFY ("PACKAGEID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ASSET_PACKAGE_MAP" ADD CONSTRAINT "PRIMARY_8" PRIMARY KEY ("APID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table STIG_ASSET_MAP
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."STIG_ASSET_MAP" MODIFY ("SAID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."STIG_ASSET_MAP" MODIFY ("STIGID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."STIG_ASSET_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."STIG_ASSET_MAP" MODIFY ("DISABLEIMPORTS" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."STIG_ASSET_MAP" ADD CONSTRAINT "PRIMARY_38" PRIMARY KEY ("SAID")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."STIG_ASSET_MAP" ADD CONSTRAINT "INDEX_2_3_C" UNIQUE ("STIGID", "ASSETID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table IMPORTED_RESULTS
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."IMPORTED_RESULTS" MODIFY ("IMPORTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATS_ASSET_STIG
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."STATS_ASSET_STIG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."STATS_ASSET_STIG" ADD CONSTRAINT "PRIMARY_31" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."STATS_ASSET_STIG" ADD CONSTRAINT "INDEX_2_2_C" UNIQUE ("ASSETID", "STIGID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUSES
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."STATUSES" MODIFY ("STATUSID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."STATUSES" MODIFY ("STATUSSTR" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."STATUSES" ADD CONSTRAINT "PRIMARY_32" PRIMARY KEY ("STATUSID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REJECT_STRINGS
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."REJECT_STRINGS" MODIFY ("REJECTID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REJECT_STRINGS" MODIFY ("SHORTSTR" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REJECT_STRINGS" ADD CONSTRAINT "PRIMARY_24" PRIMARY KEY ("REJECTID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_DATA
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."USER_DATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."USER_DATA" ADD CONSTRAINT "PRIMARY_35" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."USER_DATA" ADD CONSTRAINT "INDEX_CN" UNIQUE ("CN")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."USER_DATA" ADD CONSTRAINT "INDEX_3_C" UNIQUE ("NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table IACONTROL_IMPACT_MAP
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."IACONTROL_IMPACT_MAP" MODIFY ("IACONTROL" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."IACONTROL_IMPACT_MAP" ADD CONSTRAINT "PRIMARY_13" PRIMARY KEY ("IACONTROL")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTIONS
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."ACTIONS" MODIFY ("ACTIONID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIONS" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIONS" ADD CONSTRAINT "PRIMARY" PRIMARY KEY ("ACTIONID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTIFACT_BLOBS
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."ARTIFACT_BLOBS" MODIFY ("SHA1" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ARTIFACT_BLOBS" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ARTIFACT_BLOBS" ADD CONSTRAINT "PRIMARY_5" PRIMARY KEY ("SHA1")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW_ARTIFACT_MAP
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."REVIEW_ARTIFACT_MAP" MODIFY ("RAID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEW_ARTIFACT_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEW_ARTIFACT_MAP" MODIFY ("RULEID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEW_ARTIFACT_MAP" MODIFY ("ARTID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEW_ARTIFACT_MAP" ADD CONSTRAINT "PRIMARY_25" PRIMARY KEY ("RAID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTIVITY
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."ACTIVITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIVITY" MODIFY ("USER_" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIVITY" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIVITY" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIVITY" MODIFY ("SCRIPT" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIVITY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIVITY" ADD CONSTRAINT "PRIMARY_37" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSET_GROUPS
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."ASSET_GROUPS" MODIFY ("GROUPID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ASSET_GROUPS" ADD CONSTRAINT "PRIMARY_7" PRIMARY KEY ("GROUPID")
  USING INDEX  ENABLE;

--------------------------------------------------------
--  Constraints for Table USER_ASSET_MAP
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."USER_ASSET_MAP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."USER_ASSET_MAP" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."USER_ASSET_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."USER_ASSET_MAP" ADD CONSTRAINT "PRIMARY_34" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."USER_ASSET_MAP" ADD CONSTRAINT "INDEX_2_38" UNIQUE ("USERID", "ASSETID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTIVITY_DETAILS
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."ACTIVITY_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIVITY_DETAILS" MODIFY ("ACTIVITYID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIVITY_DETAILS" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ACTIVITY_DETAILS" ADD CONSTRAINT "PRIMARY_4" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSETS
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."ASSETS" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ASSETS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ASSETS" MODIFY ("PROFILE" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ASSETS" ADD CONSTRAINT "PRIMARY_9" PRIMARY KEY ("ASSETID")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."ASSETS" ADD CONSTRAINT "INDEX_NAME" UNIQUE ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."ASSETS" ADD CONSTRAINT "ASSETS_CHK_IP_NN" CHECK ((IP IS NOT NULL AND NONNETWORK=0) OR (IP IS NULL AND NONNETWORK=1)) ENABLE;
  ALTER TABLE "STIGMAN"."ASSETS" ADD CONSTRAINT "ASSETS_CHK_NN_SE" CHECK ((NONNETWORK = 0 and SCANEXEMPT in (0,1)) OR (NONNETWORK=1 AND SCANEXEMPT=1)) ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_STIG_ASSET_MAP
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."USER_STIG_ASSET_MAP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."USER_STIG_ASSET_MAP" ADD CONSTRAINT "PRIMARY_3" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."USER_STIG_ASSET_MAP" ADD CONSTRAINT "INDEX_2_1_C" UNIQUE ("USERID", "SAID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table PACKAGES
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."PACKAGES" MODIFY ("PACKAGEID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."PACKAGES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."PACKAGES" ADD CONSTRAINT "PRIMARY_22" PRIMARY KEY ("PACKAGEID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table POAM_RAR_ENTRIES
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."POAM_RAR_ENTRIES" MODIFY ("PREID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."POAM_RAR_ENTRIES" MODIFY ("PACKAGEID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."POAM_RAR_ENTRIES" MODIFY ("SOURCEID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."POAM_RAR_ENTRIES" ADD CONSTRAINT "PRIMARY_23" PRIMARY KEY ("PREID")
  USING INDEX  ENABLE;
  ALTER TABLE "STIGMAN"."POAM_RAR_ENTRIES" ADD CONSTRAINT "PACKAGEID_RULEID" UNIQUE ("PACKAGEID", "SOURCEID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEWS_HISTORY
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."REVIEWS_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."REVIEWS_HISTORY" ADD CONSTRAINT "PRIMARY_28" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTIFACTS
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."ARTIFACTS" MODIFY ("ARTID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ARTIFACTS" MODIFY ("SHA1" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ARTIFACTS" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ARTIFACTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ARTIFACTS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ARTIFACTS" MODIFY ("TS" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ARTIFACTS" MODIFY ("DEPT" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."ARTIFACTS" ADD CONSTRAINT "PRIMARY_6" PRIMARY KEY ("ARTID")
  USING INDEX  ENABLE;

--------------------------------------------------------
--  Constraints for Table IMPORTED_JOBS
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."IMPORTED_JOBS" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."IMPORTED_JOBS" ADD CONSTRAINT "PRIMARY_15" PRIMARY KEY ("JOBID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table STIGMAN_IDS
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."STIGMAN_IDS" MODIFY ("GUID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."STIGMAN_IDS" MODIFY ("CN" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."STIGMAN_IDS" ADD CONSTRAINT "PRIMARY_33" PRIMARY KEY ("GUID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUDITS
--------------------------------------------------------

  -- ALTER TABLE "STIGMAN"."AUDITS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."AUDITS" MODIFY ("TS" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."AUDITS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."AUDITS" MODIFY ("LOGTEXT" NOT NULL ENABLE);
  ALTER TABLE "STIGMAN"."AUDITS" ADD CONSTRAINT "PRIMARY_10" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSET_PACKAGE_MAP
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."ASSET_PACKAGE_MAP" ADD CONSTRAINT "FK_ASSET_PACKAGE_MAP_1" FOREIGN KEY ("PACKAGEID")
	  REFERENCES "STIGMAN"."PACKAGES" ("PACKAGEID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "STIGMAN"."ASSET_PACKAGE_MAP" ADD CONSTRAINT "FK_ASSET_PACKAGE_MAP_2" FOREIGN KEY ("ASSETID")
	  REFERENCES "STIGMAN"."ASSETS" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEWS
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."REVIEWS" ADD CONSTRAINT "FK_REVIEWS_1" FOREIGN KEY ("ASSETID")
	  REFERENCES "STIGMAN"."ASSETS" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW_ARTIFACT_MAP
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."REVIEW_ARTIFACT_MAP" ADD CONSTRAINT "FK_REVIEW_ARTIFACT_MAP_1" FOREIGN KEY ("ARTID")
	  REFERENCES "STIGMAN"."ARTIFACTS" ("ARTID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATS_ASSET_STIG
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."STATS_ASSET_STIG" ADD CONSTRAINT "FK_STATS_ASSET_STIG_1" FOREIGN KEY ("ASSETID")
	  REFERENCES "STIGMAN"."ASSETS" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STIG_ASSET_MAP
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."STIG_ASSET_MAP" ADD CONSTRAINT "FK_STIG_ASSET_MAP_1" FOREIGN KEY ("ASSETID")
	  REFERENCES "STIGMAN"."ASSETS" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_ROLE_MAP
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."USER_ROLE_MAP" ADD CONSTRAINT "FK_USER_ROLE_MAP_2" FOREIGN KEY ("ROLEID")
	  REFERENCES "STIGMAN"."ROLES" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "STIGMAN"."USER_ROLE_MAP" ADD CONSTRAINT "FK_USER_ROLE_MAP_1" FOREIGN KEY ("USERID")
	  REFERENCES "STIGMAN"."USER_DATA" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_STIG_ASSET_MAP
--------------------------------------------------------

  ALTER TABLE "STIGMAN"."USER_STIG_ASSET_MAP" ADD CONSTRAINT "FK_USER_STIG_ASSET_MAP_1" FOREIGN KEY ("USERID")
	  REFERENCES "STIGMAN"."USER_DATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "STIGMAN"."USER_STIG_ASSET_MAP" ADD CONSTRAINT "FK_USER_STIG_ASSET_MAP_2" FOREIGN KEY ("SAID")
	  REFERENCES "STIGMAN"."STIG_ASSET_MAP" ("SAID") ON DELETE CASCADE ENABLE;
