REM INSERTING into STIGS.SEVERITY_CAT_MAP
SET DEFINE OFF;
Insert into STIGS.SEVERITY_CAT_MAP (SEVERITY,CAT,ROMAN) values ('high','1','I');
Insert into STIGS.SEVERITY_CAT_MAP (SEVERITY,CAT,ROMAN) values ('medium','2','II');
Insert into STIGS.SEVERITY_CAT_MAP (SEVERITY,CAT,ROMAN) values ('low','3','III');
