--------------------------------------------------------
--  DDL for Table ACTION
--------------------------------------------------------

  CREATE TABLE "ACTION" 
   (	"ACTIONID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ACTION" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table ASSET
--------------------------------------------------------

  CREATE TABLE "ASSET" 
   (	"ASSETID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"IP" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"DEPARTMENTID" NUMBER DEFAULT 0, 
	"NONNETWORK" CHAR(1) COLLATE "USING_NLS_COMP" DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table ASSET_PACKAGE_MAP
--------------------------------------------------------

  CREATE TABLE "ASSET_PACKAGE_MAP" 
   (	"APID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"PACKAGEID" NUMBER(10,0), 
	"SCANRESULTID" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table CCI
--------------------------------------------------------

  CREATE TABLE "CCI" 
   (	"CCI" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"PUBDATE" DATE, 
	"CONTRIBUTOR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"TYPE" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"IMPLEMENTATION" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"APACRONYM" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"ASSESSMENTPROCEDURE" VARCHAR2(32000 CHAR) COLLATE "USING_NLS_COMP", 
	"DEFINITION" VARCHAR2(32000 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table CCI_REFERENCE_MAP
--------------------------------------------------------

  CREATE TABLE "CCI_REFERENCE_MAP" 
   (	"CRMID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CCI" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"CREATOR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"TITLE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"VERSION" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"INDEXDISA" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"TEXTREFNIST" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"PARENTCONTROL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table CHECKS
--------------------------------------------------------

  CREATE TABLE "CHECKS" 
   (	"CHECKID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"CONTENT" VARCHAR2(32000 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "DEPARTMENT" 
   (	"DEPARTMENTID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table FIX
--------------------------------------------------------

  CREATE TABLE "FIX" 
   (	"FIXID" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"TEXT" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table GROUPS
--------------------------------------------------------

  CREATE TABLE "GROUPS" 
   (	"GROUPID" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"TITLE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table PACKAGE
--------------------------------------------------------

  CREATE TABLE "PACKAGE" 
   (	"PACKAGEID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"EMASSID" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"REQRAR" NUMBER(3,0), 
	"POCNAME" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"POCEMAIL" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"POCPHONE" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table POAM_RAR_ENTRY
--------------------------------------------------------

  CREATE TABLE "POAM_RAR_ENTRY" 
   (	"PREID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PACKAGEID" NUMBER(10,0), 
	"FINDINGTYPE" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"SOURCEID" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"IACONTROL" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"POC" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"RESOURCES" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"COMPDATE" DATE, 
	"MILESTONE" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP", 
	"POAMCOMMENT" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP", 
	"LIKELIHOOD" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"MITDESC" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP", 
	"RESIDUALRISK" NUMBER(10,0), 
	"RECCORRACT" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP", 
	"REMDESC" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP", 
	"RARCOMMENT" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REJECT_STRING
--------------------------------------------------------

  CREATE TABLE "REJECT_STRING" 
   (	"REJECTID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SHORTSTR" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"LONGSTR" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table RESULT
--------------------------------------------------------

  CREATE TABLE "RESULT" 
   (	"RESULTID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RESULT" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"ABBR" VARCHAR2(3 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REV_GROUP_MAP
--------------------------------------------------------

  CREATE TABLE "REV_GROUP_MAP" 
   (	"RGID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 263717 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"GROUPID" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"REVID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REV_GROUP_RULE_CHECK_MAP
--------------------------------------------------------

  CREATE TABLE "REV_GROUP_RULE_CCI_MAP" 
   (	"RGRCID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 266797 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RGRID" NUMBER, 
	"CCI" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REV_GROUP_RULE_CHECK_MAP
--------------------------------------------------------

  CREATE TABLE "REV_GROUP_RULE_CHECK_MAP" 
   (	"RCID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 266797 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RGRID" NUMBER, 
	"CHECKID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REV_GROUP_RULE_FIX_MAP
--------------------------------------------------------

  CREATE TABLE "REV_GROUP_RULE_FIX_MAP" 
   (	"RFID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 263611 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RGRID" NUMBER, 
	"FIXID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REV_GROUP_RULE_MAP
--------------------------------------------------------

  CREATE TABLE "REV_GROUP_RULE_MAP" 
   (	"RGRID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 263857 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RGID" NUMBER(10,0), 
	"RULEID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REV_XML_MAP
--------------------------------------------------------

  CREATE TABLE "REV_XML_MAP" 
   (	"RXID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2676 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REVID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"XML" BLOB
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "REVIEW" 
   (	"REVIEWID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"RESULTID" NUMBER(10,0), 
	"USERID" NUMBER(10,0), 
	"RESULTCOMMENT" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP", 
	"ACTIONID" NUMBER(10,0), 
	"ACTIONCOMMENT" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP", 
	"AUTORESULT" NUMBER(3,0) DEFAULT '0', 
	"TS" DATE DEFAULT SYSDATE, 
	"REJECTTEXT" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP", 
	"REJECTUSERID" NUMBER(10,0), 
	"STATUSID" NUMBER(10,0) DEFAULT '0'
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REVIEW_HISTORY
--------------------------------------------------------

  CREATE TABLE "REVIEW_HISTORY" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"ACTIVITYTYPE" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"COLUMNNAME" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"OLDVALUE" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP", 
	"NEWVALUE" VARCHAR2(32766 CHAR) COLLATE "USING_NLS_COMP", 
	"USERID" NUMBER(10,0), 
	"TS" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REVIEW_REJECT_STRING_MAP
--------------------------------------------------------

  CREATE TABLE "REVIEW_REJECT_STRING_MAP" 
   (	"RRSID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"RULEID" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"REJECTID" NUMBER(10,0), 
	"USERID" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table REVISION
--------------------------------------------------------

  CREATE TABLE "REVISION" 
   (	"REVID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"BENCHMARKID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"VERSION" NUMBER(10,0), 
	"RELEASE" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"BENCHMARKDATE" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"BENCHMARKDATESQL" DATE, 
	"STATUS" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"STATUSDATE" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"ACTIVE" NUMBER(3,0) DEFAULT '1', 
	"SHA1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "ROLE" 
   (	"ROLEID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"DISPLAY" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table RULE
--------------------------------------------------------

  CREATE TABLE "RULE" 
   (	"RULEID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"VERSION" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"TITLE" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"SEVERITY" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"WEIGHT" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"VULNDISCUSSION" VARCHAR2(32000 CHAR) COLLATE "USING_NLS_COMP", 
	"FALSEPOSITIVES" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"FALSENEGATIVES" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"DOCUMENTABLE" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"MITIGATIONS" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"SEVERITYOVERRIDEGUIDANCE" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"POTENTIALIMPACTS" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"THIRDPARTYTOOLS" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"MITIGATIONCONTROL" VARCHAR2(32000 CHAR) COLLATE "USING_NLS_COMP", 
	"RESPONSIBILITY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"IACONTROLS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table RULE_CONTROL_MAP
--------------------------------------------------------

  CREATE TABLE "RULE_CONTROL_MAP" 
   (	"RCTLID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 303723 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RULEID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"CONTROLNUMBER" VARCHAR2(60) COLLATE "USING_NLS_COMP", 
	"CONTROLTYPE" VARCHAR2(60) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table RULE_OVAL_MAP
--------------------------------------------------------

  CREATE TABLE "RULE_OVAL_MAP" 
   (	"ROID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 54978 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RULEID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"OVALREF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"BENCHMARKID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"RELEASEINFO" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table SEVERITY_CAT_MAP
--------------------------------------------------------

  CREATE TABLE "SEVERITY_CAT_MAP" 
   (	"SCID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SEVERITY" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"CAT" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP", 
	"ROMAN" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table STATS_ASSET_STIG
--------------------------------------------------------

  CREATE TABLE "STATS_ASSET_STIG" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ASSETID" NUMBER(10,0), 
	"BENCHMARKID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"MINTS" DATE, 
	"MAXTS" DATE, 
	"CHECKSMANUAL" NUMBER(10,0), 
	"CHECKSSCAP" NUMBER(10,0), 
	"INPROGRESSMANUAL" NUMBER(10,0), 
	"INPROGRESSSCAP" NUMBER(10,0), 
	"SUBMITTEDMANUAL" NUMBER(10,0), 
	"SUBMITTEDSCAP" NUMBER(10,0), 
	"REJECTEDMANUAL" NUMBER(10,0), 
	"REJECTEDSCAP" NUMBER(10,0), 
	"ACCEPTEDMANUAL" NUMBER(10,0), 
	"ACCEPTEDSCAP" NUMBER(10,0), 
	"CAT1COUNT" NUMBER(10,0), 
	"CAT2COUNT" NUMBER(10,0), 
	"CAT3COUNT" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table STATUS
--------------------------------------------------------

  CREATE TABLE "STATUS" 
   (	"STATUSID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STATUSSTR" VARCHAR2(45 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table STIG
--------------------------------------------------------

  CREATE TABLE "STIG" 
   (	"BENCHMARKID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"TITLE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table STIG_ASSET_MAP
--------------------------------------------------------

  CREATE TABLE "STIG_ASSET_MAP" 
   (	"SAID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"BENCHMARKID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"ASSETID" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table USER_DATA
--------------------------------------------------------

  CREATE TABLE "USER_DATA" 
   (	"USERID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"DISPLAY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"DEPARTMENTID" NUMBER DEFAULT 0, 
	"ROLEID" NUMBER(10,0) DEFAULT 1, 
	"CANADMIN" NUMBER(3,0) DEFAULT '0'
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table USER_STIG_ASSET_MAP
--------------------------------------------------------

  CREATE TABLE "USER_STIG_ASSET_MAP" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" NUMBER(10,0), 
	"SAID" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for View CURRENT_REV
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "CURRENT_REV" ("REVID", "BENCHMARKID", "VERSION", "RELEASE", "BENCHMARKDATE", "BENCHMARKDATESQL", "STATUS", "STATUSDATE", "DESCRIPTION", "ACTIVE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select
    rr.revId,
    rr.benchmarkId,
    rr.version,
    rr.release,
    rr.benchmarkDate,
    rr.benchmarkDateSql,
    rr.status,
    rr.statusDate,
    rr.description,
    rr.active
from
    (select
        r.revId,
        r.benchmarkId,
        r.version,
        r.release,
        r.benchmarkDate,
        r.benchmarkDateSql,
        r.status,
        r.statusDate,
        r.description,
        r.active,
        row_number() OVER (partition by r.benchmarkId order by (r.version+0) desc, (r.release+0) desc) as rn
    FROM
        revision r) rr
where rr.rn =1
;
--------------------------------------------------------
--  DDL for Index UK_ACTION_ACTIONID
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_ACTION_ACTIONID" ON "ACTION" ("ACTIONID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_ASSET_4
--------------------------------------------------------

  CREATE INDEX "IDX_ASSET_4" ON "ASSET" ("NONNETWORK") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_ASSET_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_ASSET_1" ON "ASSET" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_ASSET_2
--------------------------------------------------------

  CREATE INDEX "IDX_ASSET_2" ON "ASSET" ("DEPARTMENTID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_ASSET_3
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_ASSET_3" ON "ASSET" ("NAME") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_APM_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_APM_2" ON "ASSET_PACKAGE_MAP" ("PACKAGEID", "ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_APM_4
--------------------------------------------------------

  CREATE INDEX "IDX_APM_4" ON "ASSET_PACKAGE_MAP" ("PACKAGEID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_APM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_APM_1" ON "ASSET_PACKAGE_MAP" ("APID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_APM_3
--------------------------------------------------------

  CREATE INDEX "IDX_APM_3" ON "ASSET_PACKAGE_MAP" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CCI_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_CCI_1" ON "CCI" ("CCI") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CCI_2
--------------------------------------------------------

  CREATE INDEX "IDX_CCI_2" ON "CCI" ("APACRONYM") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CRM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_CRM_1" ON "CCI_REFERENCE_MAP" ("CRMID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CRM_2
--------------------------------------------------------

  CREATE INDEX "IDX_CRM_2" ON "CCI_REFERENCE_MAP" ("CCI") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_CHECKS_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_CHECKS_1" ON "CHECKS" ("CHECKID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_DEPT_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_DEPT_1" ON "DEPARTMENT" ("DEPARTMENTID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_DEPT_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_DEPT_2" ON "DEPARTMENT" ("NAME") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_FIX_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_FIX_1" ON "FIX" ("FIXID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_GROUPS
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_GROUPS" ON "GROUPS" ("GROUPID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_PACKAGE_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_PACKAGE_1" ON "PACKAGE" ("PACKAGEID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_PRENTRY_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_PRENTRY_1" ON "POAM_RAR_ENTRY" ("PREID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_PRENTRY_3
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_PRENTRY_3" ON "POAM_RAR_ENTRY" ("PACKAGEID", "SOURCEID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_PRENTRY_2
--------------------------------------------------------

  CREATE INDEX "IDX_PRENTRY_2" ON "POAM_RAR_ENTRY" ("FINDINGTYPE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_REJECT_STRING_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_REJECT_STRING_1" ON "REJECT_STRING" ("REJECTID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RESULT_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RESULT_1" ON "RESULT" ("RESULTID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RGM_1" ON "REV_GROUP_MAP" ("RGID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGM_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RGM_2" ON "REV_GROUP_MAP" ("GROUPID", "REVID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGM_3
--------------------------------------------------------

  CREATE INDEX "IDX_RGM_3" ON "REV_GROUP_MAP" ("REVID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRCCIM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RGRCM2_1" ON "REV_GROUP_RULE_CCI_MAP" ("RGRCID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRCCIM_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RGRCM2_2" ON "REV_GROUP_RULE_CCI_MAP" ("RGRID", "CCI") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRCCIM_3
--------------------------------------------------------

  CREATE INDEX "IDX_RGRCM2_3" ON "REV_GROUP_RULE_CCI_MAP" ("CCI") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRCM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RGRCM_1" ON "REV_GROUP_RULE_CHECK_MAP" ("RCID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRCM_3
--------------------------------------------------------

  CREATE INDEX "IDX_RGRCM_3" ON "REV_GROUP_RULE_CHECK_MAP" ("CHECKID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRCM_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RGRCM_2" ON "REV_GROUP_RULE_CHECK_MAP" ("RGRID", "CHECKID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRFM_3
--------------------------------------------------------

  CREATE INDEX "IDX_RGRFM_3" ON "REV_GROUP_RULE_FIX_MAP" ("FIXID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRFM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RGRFM_1" ON "REV_GROUP_RULE_FIX_MAP" ("RFID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRFM_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RGRFM_2" ON "REV_GROUP_RULE_FIX_MAP" ("RGRID", "FIXID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RGRM_1" ON "REV_GROUP_RULE_MAP" ("RGRID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRM_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RGRM_2" ON "REV_GROUP_RULE_MAP" ("RULEID", "RGID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RGRM_3
--------------------------------------------------------

  CREATE INDEX "IDX_RGRM_3" ON "REV_GROUP_RULE_MAP" ("RGID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RXM_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RXM_2" ON "REV_XML_MAP" ("REVID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RXM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RXM_1" ON "REV_XML_MAP" ("RXID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_REVIEW_4
--------------------------------------------------------

  CREATE INDEX "IDX_REVIEW_4" ON "REVIEW" ("RESULTID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_REVIEW_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_REVIEW_1" ON "REVIEW" ("REVIEWID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_REVIEW_3
--------------------------------------------------------

  CREATE INDEX "IDX_REVIEW_3" ON "REVIEW" ("RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_REVIEW_5
--------------------------------------------------------

  CREATE INDEX "IDX_REVIEW_5" ON "REVIEW" ("STATUSID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_REVIEW_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_REVIEW_2" ON "REVIEW" ("ASSETID", "RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RH_2
--------------------------------------------------------

  CREATE INDEX "IDX_RH_2" ON "REVIEW_HISTORY" ("ACTIVITYTYPE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RH_3
--------------------------------------------------------

  CREATE INDEX "IDX_RH_3" ON "REVIEW_HISTORY" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RH_4
--------------------------------------------------------

  CREATE INDEX "IDX_RH_4" ON "REVIEW_HISTORY" ("COLUMNNAME") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RH_5
--------------------------------------------------------

  CREATE INDEX "IDX_RH_5" ON "REVIEW_HISTORY" ("RULEID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RH_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RH_1" ON "REVIEW_HISTORY" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RRSM_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RRSM_2" ON "REVIEW_REJECT_STRING_MAP" ("ASSETID", "RULEID", "REJECTID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RRSM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RRSM_1" ON "REVIEW_REJECT_STRING_MAP" ("RRSID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_REVISION_2
--------------------------------------------------------

  CREATE INDEX "IDX_REVISION_2" ON "REVISION" ("BENCHMARKID", "VERSION", "RELEASE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_REVISION_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_REVISION_1" ON "REVISION" ("REVID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_ROLE_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_ROLE_1" ON "ROLE" ("ROLEID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_RULE_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_RULE_1" ON "RULE" ("RULEID", "VERSION") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_15
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_15" ON "RULE_CONTROL_MAP" ("RCTLID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_3
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX_2_3" ON "RULE_CONTROL_MAP" ("RULEID", "CONTROLNUMBER") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_3_2
--------------------------------------------------------

  CREATE INDEX "INDEX_3_2" ON "RULE_CONTROL_MAP" ("CONTROLNUMBER") 
  ;
--------------------------------------------------------
--  DDL for Index PRIMARY_17
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRIMARY_17" ON "RULE_OVAL_MAP" ("ROID") 
  ;
--------------------------------------------------------
--  DDL for Index INDEX_2_5
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX_2_5" ON "RULE_OVAL_MAP" ("RULEID", "OVALREF", "BENCHMARKID", "RELEASEINFO") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_SCM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_SCM_1" ON "SEVERITY_CAT_MAP" ("SCID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_SAS_3
--------------------------------------------------------

  CREATE INDEX "IDX_SAS_3" ON "STATS_ASSET_STIG" ("BENCHMARKID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_SAS_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_SAS_1" ON "STATS_ASSET_STIG" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_SAS_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_SAS_2" ON "STATS_ASSET_STIG" ("ASSETID", "BENCHMARKID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_STATUS_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_STATUS_1" ON "STATUS" ("STATUSID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_STIG_2
--------------------------------------------------------

  CREATE INDEX "IDX_STIG_2" ON "STIG" ("TITLE") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_STIG_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_STIG_1" ON "STIG" ("BENCHMARKID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_SAM_3
--------------------------------------------------------

  CREATE INDEX "IDX_SAM_3" ON "STIG_ASSET_MAP" ("ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_SAM_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_SAM_2" ON "STIG_ASSET_MAP" ("BENCHMARKID", "ASSETID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_SAM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_SAM_1" ON "STIG_ASSET_MAP" ("SAID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_USER_DATA_4
--------------------------------------------------------

  CREATE INDEX "IDX_USER_DATA_4" ON "USER_DATA" ("DEPARTMENTID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_USER_DATA_3
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_USER_DATA_3" ON "USER_DATA" ("DISPLAY") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_USER_DATA_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_USER_DATA_1" ON "USER_DATA" ("USERID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_USER_DATA_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_USER_DATA_2" ON "USER_DATA" ("USERNAME") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_USER_DATA_5
--------------------------------------------------------

  CREATE INDEX "IDX_USER_DATA_5" ON "USER_DATA" ("ROLEID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_USER_DATA_6
--------------------------------------------------------

  CREATE INDEX "IDX_USER_DATA_6" ON "USER_DATA" ("CANADMIN") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_USAM_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_USAM_2" ON "USER_STIG_ASSET_MAP" ("USERID", "SAID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_USAM_3
--------------------------------------------------------

  CREATE INDEX "IDX_USAM_3" ON "USER_STIG_ASSET_MAP" ("SAID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_USAM_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_USAM_1" ON "USER_STIG_ASSET_MAP" ("ID") 
  ;
--------------------------------------------------------
--  Constraints for Table ACTION
--------------------------------------------------------
  ALTER TABLE "ACTION" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "ACTION" ADD CONSTRAINT "PK_ACTION" PRIMARY KEY ("ACTIONID")
  USING INDEX "UK_ACTION_ACTIONID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSET
--------------------------------------------------------
  ALTER TABLE "ASSET" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ASSET" ADD CONSTRAINT "PK_ASSET" PRIMARY KEY ("ASSETID")
  USING INDEX "IDX_ASSET_1"  ENABLE;
  ALTER TABLE "ASSET" ADD CONSTRAINT "UK_ASSET_NAME" UNIQUE ("NAME")
  USING INDEX "IDX_ASSET_3"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSET_PACKAGE_MAP
--------------------------------------------------------
  ALTER TABLE "ASSET_PACKAGE_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "ASSET_PACKAGE_MAP" MODIFY ("PACKAGEID" NOT NULL ENABLE);
  ALTER TABLE "ASSET_PACKAGE_MAP" ADD CONSTRAINT "PK_APM" PRIMARY KEY ("APID")
  USING INDEX "IDX_APM_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CCI
--------------------------------------------------------

  ALTER TABLE "CCI" ADD CONSTRAINT "PK_CCI" PRIMARY KEY ("CCI")
  USING INDEX "IDX_CCI_1"  ENABLE;
  ALTER TABLE "CCI" MODIFY ("CCI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CCI_REFERENCE_MAP
--------------------------------------------------------
  ALTER TABLE "CCI_REFERENCE_MAP" ADD CONSTRAINT "PK_CRM" PRIMARY KEY ("CRMID")
  USING INDEX "IDX_CRM_1"  ENABLE;
  ALTER TABLE "CCI_REFERENCE_MAP" MODIFY ("CCI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHECKS
--------------------------------------------------------
  ALTER TABLE "CHECKS" MODIFY ("CHECKID" NOT NULL ENABLE);
  ALTER TABLE "CHECKS" ADD CONSTRAINT "PK_CHECKS" PRIMARY KEY ("CHECKID")
  USING INDEX "IDX_CHECKS_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------
  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY ("DEPARTMENTID")
  USING INDEX "IDX_DEPT_1"  ENABLE;
  ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "UK_DEPT_2" UNIQUE ("NAME")
  USING INDEX "IDX_DEPT_2"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FIX
--------------------------------------------------------

  ALTER TABLE "FIX" MODIFY ("FIXID" NOT NULL ENABLE);
  ALTER TABLE "FIX" MODIFY ("TEXT" NOT NULL ENABLE);
  ALTER TABLE "FIX" ADD CONSTRAINT "PK_FIX" PRIMARY KEY ("FIXID")
  USING INDEX "IDX_FIX_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GROUPS
--------------------------------------------------------
  ALTER TABLE "GROUPS" MODIFY ("GROUPID" NOT NULL ENABLE);
  ALTER TABLE "GROUPS" ADD CONSTRAINT "PK_GROUPS" PRIMARY KEY ("GROUPID")
  USING INDEX "IDX_GROUPS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PACKAGE
--------------------------------------------------------
  ALTER TABLE "PACKAGE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PACKAGE" ADD CONSTRAINT "PK_PACKAGE" PRIMARY KEY ("PACKAGEID")
  USING INDEX "IDX_PACKAGE_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POAM_RAR_ENTRY
--------------------------------------------------------
  ALTER TABLE "POAM_RAR_ENTRY" MODIFY ("PACKAGEID" NOT NULL ENABLE);
  ALTER TABLE "POAM_RAR_ENTRY" MODIFY ("SOURCEID" NOT NULL ENABLE);
  ALTER TABLE "POAM_RAR_ENTRY" ADD CONSTRAINT "PK_POAM_RAR_ENTRY" PRIMARY KEY ("PREID")
  USING INDEX "IDX_PRENTRY_1"  ENABLE;
  ALTER TABLE "POAM_RAR_ENTRY" ADD CONSTRAINT "UK_POAM_RAR_ENTRY_1" UNIQUE ("PACKAGEID", "SOURCEID")
  USING INDEX "IDX_PRENTRY_3"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REJECT_STRING
--------------------------------------------------------
  ALTER TABLE "REJECT_STRING" MODIFY ("SHORTSTR" NOT NULL ENABLE);
  ALTER TABLE "REJECT_STRING" ADD CONSTRAINT "PRIMARY_24" PRIMARY KEY ("REJECTID")
  USING INDEX "IDX_REJECT_STRING_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESULT
--------------------------------------------------------
  ALTER TABLE "RESULT" ADD CONSTRAINT "PK_RESULT" PRIMARY KEY ("RESULTID")
  USING INDEX "IDX_RESULT_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REV_GROUP_MAP
--------------------------------------------------------
  ALTER TABLE "REV_GROUP_MAP" MODIFY ("GROUPID" NOT NULL ENABLE);
  ALTER TABLE "REV_GROUP_MAP" MODIFY ("REVID" NOT NULL ENABLE);
  ALTER TABLE "REV_GROUP_MAP" ADD CONSTRAINT "PK_RGM" PRIMARY KEY ("RGID")
  USING INDEX "IDX_RGM_1"  ENABLE;
  ALTER TABLE "REV_GROUP_MAP" ADD CONSTRAINT "UK_RGM_2" UNIQUE ("GROUPID", "REVID")
  USING INDEX "IDX_RGM_2"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REV_GROUP_RULE_CCI_MAP
--------------------------------------------------------
  ALTER TABLE "REV_GROUP_RULE_CCI_MAP" MODIFY ("RGRID" NOT NULL ENABLE);
  ALTER TABLE "REV_GROUP_RULE_CCI_MAP" MODIFY ("CCI" NOT NULL ENABLE);
  ALTER TABLE "REV_GROUP_RULE_CCI_MAP" ADD CONSTRAINT "PK_RGRCM2" PRIMARY KEY ("RGRCID")
  USING INDEX "IDX_RGRCM2_1"  ENABLE;
  ALTER TABLE "REV_GROUP_RULE_CCI_MAP" ADD CONSTRAINT "UK_RGRCM2_2" UNIQUE ("RGRID", "CCI")
  USING INDEX "IDX_RGRCM2_2"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REV_GROUP_RULE_CHECK_MAP
--------------------------------------------------------
  ALTER TABLE "REV_GROUP_RULE_CHECK_MAP" MODIFY ("RGRID" NOT NULL ENABLE);
  ALTER TABLE "REV_GROUP_RULE_CHECK_MAP" MODIFY ("CHECKID" NOT NULL ENABLE);
  ALTER TABLE "REV_GROUP_RULE_CHECK_MAP" ADD CONSTRAINT "PK_RGRCM" PRIMARY KEY ("RCID")
  USING INDEX "IDX_RGRCM_1"  ENABLE;
  ALTER TABLE "REV_GROUP_RULE_CHECK_MAP" ADD CONSTRAINT "UK_RGRCM_2" UNIQUE ("RGRID", "CHECKID")
  USING INDEX "IDX_RGRCM_2"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REV_GROUP_RULE_FIX_MAP
--------------------------------------------------------
  ALTER TABLE "REV_GROUP_RULE_FIX_MAP" MODIFY ("RGRID" NOT NULL ENABLE);
  ALTER TABLE "REV_GROUP_RULE_FIX_MAP" MODIFY ("FIXID" NOT NULL ENABLE);
  ALTER TABLE "REV_GROUP_RULE_FIX_MAP" ADD CONSTRAINT "PK_RGRFM" PRIMARY KEY ("RFID")
  USING INDEX "IDX_RGRFM_1"  ENABLE;
  ALTER TABLE "REV_GROUP_RULE_FIX_MAP" ADD CONSTRAINT "UK_RGRFM_2" UNIQUE ("RGRID", "FIXID")
  USING INDEX "IDX_RGRFM_2"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REV_GROUP_RULE_MAP
--------------------------------------------------------
  ALTER TABLE "REV_GROUP_RULE_MAP" ADD CONSTRAINT "PK_RGRM" PRIMARY KEY ("RGRID")
  USING INDEX "IDX_RGRM_1"  ENABLE;
  ALTER TABLE "REV_GROUP_RULE_MAP" ADD CONSTRAINT "UK_RGRM_2" UNIQUE ("RULEID", "RGID")
  USING INDEX "IDX_RGRM_2"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REV_XML_MAP
--------------------------------------------------------
  ALTER TABLE "REV_XML_MAP" MODIFY ("REVID" NOT NULL ENABLE);
  ALTER TABLE "REV_XML_MAP" ADD CONSTRAINT "PK_RXM" PRIMARY KEY ("RXID")
  USING INDEX "IDX_RXM_1"  ENABLE;
  ALTER TABLE "REV_XML_MAP" ADD CONSTRAINT "UK_RXM_2" UNIQUE ("REVID")
  USING INDEX "IDX_RXM_2"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------
  ALTER TABLE "REVIEW" MODIFY ("TS" NOT NULL ENABLE);
  ALTER TABLE "REVIEW" MODIFY ("STATUSID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW" ADD CONSTRAINT "UK_REVIEW_2" UNIQUE ("ASSETID", "RULEID")
  USING INDEX "IDX_REVIEW_2"  ENABLE;
  ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("REVIEWID")
  USING INDEX "IDX_REVIEW_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW_HISTORY
--------------------------------------------------------
  ALTER TABLE "REVIEW_HISTORY" ADD CONSTRAINT "PK_RH" PRIMARY KEY ("ID")
  USING INDEX "IDX_RH_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW_REJECT_STRING_MAP
--------------------------------------------------------
  ALTER TABLE "REVIEW_REJECT_STRING_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_REJECT_STRING_MAP" MODIFY ("RULEID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_REJECT_STRING_MAP" MODIFY ("REJECTID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW_REJECT_STRING_MAP" ADD CONSTRAINT "PK_RRSM" PRIMARY KEY ("RRSID")
  USING INDEX "IDX_RRSM_1"  ENABLE;
  ALTER TABLE "REVIEW_REJECT_STRING_MAP" ADD CONSTRAINT "UK_RRSM_2" UNIQUE ("ASSETID", "RULEID", "REJECTID")
  USING INDEX "IDX_RRSM_2"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVISION
--------------------------------------------------------
  ALTER TABLE "REVISION" MODIFY ("REVID" NOT NULL ENABLE);
  ALTER TABLE "REVISION" MODIFY ("BENCHMARKID" NOT NULL ENABLE);
  ALTER TABLE "REVISION" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "REVISION" MODIFY ("RELEASE" NOT NULL ENABLE);
  ALTER TABLE "REVISION" ADD CONSTRAINT "PK_REVISION" PRIMARY KEY ("REVID")
  USING INDEX "IDX_REVISION_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------
  ALTER TABLE "ROLE" ADD CONSTRAINT "PK_ROLE" PRIMARY KEY ("ROLEID")
  USING INDEX "IDX_ROLE_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RULE
--------------------------------------------------------
  ALTER TABLE "RULE" MODIFY ("RULEID" NOT NULL ENABLE);
  ALTER TABLE "RULE" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "RULE" ADD CONSTRAINT "PK_RULE" PRIMARY KEY ("RULEID", "VERSION")
  USING INDEX "IDX_RULE_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RULE_CONTROL_MAP
--------------------------------------------------------
  ALTER TABLE "RULE_CONTROL_MAP" MODIFY ("RULEID" NOT NULL ENABLE);
  ALTER TABLE "RULE_CONTROL_MAP" MODIFY ("CONTROLNUMBER" NOT NULL ENABLE);
  ALTER TABLE "RULE_CONTROL_MAP" ADD CONSTRAINT "PRIMARY_15" PRIMARY KEY ("RCTLID")
  USING INDEX "PRIMARY_15"  ENABLE;
  ALTER TABLE "RULE_CONTROL_MAP" ADD CONSTRAINT "INDEX_2_3" UNIQUE ("RULEID", "CONTROLNUMBER")
  USING INDEX "INDEX_2_3"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RULE_OVAL_MAP
--------------------------------------------------------
  ALTER TABLE "RULE_OVAL_MAP" MODIFY ("RULEID" NOT NULL ENABLE);
  ALTER TABLE "RULE_OVAL_MAP" MODIFY ("BENCHMARKID" NOT NULL ENABLE);
  ALTER TABLE "RULE_OVAL_MAP" ADD CONSTRAINT "PRIMARY_17" PRIMARY KEY ("ROID")
  USING INDEX "PRIMARY_17"  ENABLE;
  ALTER TABLE "RULE_OVAL_MAP" ADD CONSTRAINT "INDEX_2_5" UNIQUE ("RULEID", "OVALREF", "BENCHMARKID", "RELEASEINFO")
  USING INDEX "INDEX_2_5"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEVERITY_CAT_MAP
--------------------------------------------------------
  ALTER TABLE "SEVERITY_CAT_MAP" MODIFY ("SEVERITY" NOT NULL ENABLE);
  ALTER TABLE "SEVERITY_CAT_MAP" MODIFY ("CAT" NOT NULL ENABLE);
  ALTER TABLE "SEVERITY_CAT_MAP" MODIFY ("ROMAN" NOT NULL ENABLE);
  ALTER TABLE "SEVERITY_CAT_MAP" ADD CONSTRAINT "PK_SCM" PRIMARY KEY ("SCID")
  USING INDEX "IDX_SCM_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATS_ASSET_STIG
--------------------------------------------------------
  ALTER TABLE "STATS_ASSET_STIG" ADD CONSTRAINT "PK_SAS" PRIMARY KEY ("ID")
  USING INDEX "IDX_SAS_1"  ENABLE;
  ALTER TABLE "STATS_ASSET_STIG" ADD CONSTRAINT "UK_SAS_2" UNIQUE ("ASSETID", "BENCHMARKID")
  USING INDEX "IDX_SAS_2"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUS
--------------------------------------------------------
  ALTER TABLE "STATUS" MODIFY ("STATUSSTR" NOT NULL ENABLE);
  ALTER TABLE "STATUS" ADD CONSTRAINT "PK_STATUS" PRIMARY KEY ("STATUSID")
  USING INDEX "IDX_STATUS_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STIG
--------------------------------------------------------
  ALTER TABLE "STIG" MODIFY ("BENCHMARKID" NOT NULL ENABLE);
  ALTER TABLE "STIG" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "STIG" ADD CONSTRAINT "PK_STIG" PRIMARY KEY ("BENCHMARKID")
  USING INDEX "IDX_STIG_1"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STIG_ASSET_MAP
--------------------------------------------------------
  ALTER TABLE "STIG_ASSET_MAP" MODIFY ("BENCHMARKID" NOT NULL ENABLE);
  ALTER TABLE "STIG_ASSET_MAP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "STIG_ASSET_MAP" ADD CONSTRAINT "PK_SAM" PRIMARY KEY ("SAID")
  USING INDEX "IDX_SAM_1"  ENABLE;
  ALTER TABLE "STIG_ASSET_MAP" ADD CONSTRAINT "UK_SAM_2" UNIQUE ("BENCHMARKID", "ASSETID")
  USING INDEX "IDX_SAM_2"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_DATA
--------------------------------------------------------
  ALTER TABLE "USER_DATA" ADD CONSTRAINT "PK_USER_DATA" PRIMARY KEY ("USERID")
  USING INDEX "IDX_USER_DATA_1"  ENABLE;
  ALTER TABLE "USER_DATA" ADD CONSTRAINT "UK_USER_DATA_2" UNIQUE ("USERNAME")
  USING INDEX "IDX_USER_DATA_2"  ENABLE;
  ALTER TABLE "USER_DATA" ADD CONSTRAINT "UK_USER_DATA_3" UNIQUE ("DISPLAY")
  USING INDEX "IDX_USER_DATA_3"  ENABLE;
  ALTER TABLE "USER_DATA" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "USER_DATA" MODIFY ("DISPLAY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_STIG_ASSET_MAP
--------------------------------------------------------
  ALTER TABLE "USER_STIG_ASSET_MAP" ADD CONSTRAINT "PK_USAM" PRIMARY KEY ("ID")
  USING INDEX "IDX_USAM_1"  ENABLE;
  ALTER TABLE "USER_STIG_ASSET_MAP" ADD CONSTRAINT "UK_USAM_2" UNIQUE ("USERID", "SAID")
  USING INDEX "IDX_USAM_2"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSET
--------------------------------------------------------

  ALTER TABLE "ASSET" ADD CONSTRAINT "FK_DEPT_ASSET_1" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "DEPARTMENT" ("DEPARTMENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSET_PACKAGE_MAP
--------------------------------------------------------

  ALTER TABLE "ASSET_PACKAGE_MAP" ADD CONSTRAINT "FK_PACKAGE_APM_1" FOREIGN KEY ("PACKAGEID")
	  REFERENCES "PACKAGE" ("PACKAGEID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ASSET_PACKAGE_MAP" ADD CONSTRAINT "FK_ASSET_APM_1" FOREIGN KEY ("ASSETID")
	  REFERENCES "ASSET" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REV_GROUP_MAP
--------------------------------------------------------

  ALTER TABLE "REV_GROUP_MAP" ADD CONSTRAINT "FK_REVISIONS_RGM_1" FOREIGN KEY ("REVID")
	  REFERENCES "REVISION" ("REVID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REV_GROUP_RULE_CHECK_MAP
--------------------------------------------------------

  ALTER TABLE "REV_GROUP_RULE_CHECK_MAP" ADD CONSTRAINT "FK_RGRM_RGRCM_1" FOREIGN KEY ("RGRID")
	  REFERENCES "REV_GROUP_RULE_MAP" ("RGRID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REV_GROUP_RULE_FIX_MAP
--------------------------------------------------------

  ALTER TABLE "REV_GROUP_RULE_FIX_MAP" ADD CONSTRAINT "FK_RGRM_RGRFM_1" FOREIGN KEY ("RGRID")
	  REFERENCES "REV_GROUP_RULE_MAP" ("RGRID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REV_GROUP_RULE_MAP
--------------------------------------------------------

  ALTER TABLE "REV_GROUP_RULE_MAP" ADD CONSTRAINT "FK_RGM_RGRM_1" FOREIGN KEY ("RGID")
	  REFERENCES "REV_GROUP_MAP" ("RGID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REV_XML_MAP
--------------------------------------------------------

  ALTER TABLE "REV_XML_MAP" ADD CONSTRAINT "FK_REVISIONS_RXM_1" FOREIGN KEY ("REVID")
	  REFERENCES "REVISION" ("REVID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_ASSET_REVIEW_1" FOREIGN KEY ("ASSETID")
	  REFERENCES "ASSET" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVISION
--------------------------------------------------------

  ALTER TABLE "REVISION" ADD CONSTRAINT "FK_STIG_REVISION_1" FOREIGN KEY ("BENCHMARKID")
	  REFERENCES "STIG" ("BENCHMARKID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATS_ASSET_STIG
--------------------------------------------------------

  ALTER TABLE "STATS_ASSET_STIG" ADD CONSTRAINT "FK_ASSET_SAS_1" FOREIGN KEY ("ASSETID")
	  REFERENCES "ASSET" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STIG_ASSET_MAP
--------------------------------------------------------

  ALTER TABLE "STIG_ASSET_MAP" ADD CONSTRAINT "FK_ASSET_SAM_1" FOREIGN KEY ("ASSETID")
	  REFERENCES "ASSET" ("ASSETID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_DATA
--------------------------------------------------------

  ALTER TABLE "USER_DATA" ADD CONSTRAINT "FK_DEPT_USER_DATA_1" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "DEPARTMENT" ("DEPARTMENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_STIG_ASSET_MAP
--------------------------------------------------------

  ALTER TABLE "USER_STIG_ASSET_MAP" ADD CONSTRAINT "FK_USER_DATA_USAM_1" FOREIGN KEY ("USERID")
	  REFERENCES "USER_DATA" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "USER_STIG_ASSET_MAP" ADD CONSTRAINT "FK_SAM_USAM_1" FOREIGN KEY ("SAID")
	  REFERENCES "STIG_ASSET_MAP" ("SAID") ON DELETE CASCADE ENABLE;
