INSERT INTO action VALUES (1,'Remediate');
INSERT INTO action VALUES (2,'Mitigate');
INSERT INTO action VALUES (3,'Exception');
INSERT INTO reject_string VALUES (1,'Evaluation comment not specific.','The comment supporting the result of the evaluation does not contain enough specific information. Comments should mention the specific setting(s) or value(s) contained in the check text.');
INSERT INTO reject_string VALUES (2,'Recommendation comment not specific.','The comment describing the recommended action is not specific.');
INSERT INTO reject_string VALUES (3,'Documentation is not attached.','The review requires the submission of documentation for the result of the evaluation to be accepted.');
INSERT INTO role VALUES (1,'Guest','Guest Viewer');
INSERT INTO role VALUES (2,'IAWF','IA Workforce');
INSERT INTO role VALUES (3,'IAO','IA Officer');
INSERT INTO role VALUES (4,'Staff','IA Staff');
INSERT INTO result VALUES (1,'In Process','IP');
INSERT INTO result VALUES (2,'Not Applicable','NA');
INSERT INTO result VALUES (3,'Not a Finding','NF');
INSERT INTO result VALUES (4,'Open','O');
INSERT INTO status VALUES (0,'saved');
INSERT INTO status VALUES (1,'submitted');
INSERT INTO status VALUES (2,'rejected');
INSERT INTO status VALUES (3,'accepted');
INSERT INTO department VALUES (0,'Default');
commit;
