INSERT INTO action VALUES (1,'remediate','Remediate');
INSERT INTO action VALUES (2,'mitigate','Mitigate');
INSERT INTO action VALUES (3,'exception','Exception');
INSERT INTO reject_string VALUES (1,'Evaluation comment not specific.','The comment supporting the result of the evaluation does not contain enough specific information. Comments should mention the specific setting(s) or value(s) contained in the check text.');
INSERT INTO reject_string VALUES (2,'Recommendation comment not specific.','The comment describing the recommended action is not specific.');
INSERT INTO reject_string VALUES (3,'Documentation is not attached.','The review requires the submission of documentation for the result of the evaluation to be accepted.');
INSERT INTO role VALUES (1,'Guest','Guest Viewer');
INSERT INTO role VALUES (2,'REVIEWER','IA Workforce');
INSERT INTO role VALUES (3,'DEPT','IA Officer');
INSERT INTO role VALUES (4,'COMMAND','IA Staff');
INSERT INTO result VALUES (1,'notchecked','Not_Reviewed','NR','Not checked');
INSERT INTO result VALUES (2,'notapplicable','Not_Applicable','NA','Not Applicable');
INSERT INTO result VALUES (3,'pass','NotAFinding','NF','Not a Finding');
INSERT INTO result VALUES (4,'fail','Open','O','Open');
INSERT INTO result VALUES (5,'unknown','Not_Reviewed','U','Unknown');
INSERT INTO result VALUES (6,'error','Not_Reviewed','E','Error');
INSERT INTO result VALUES (7,'notselected','Not_Reviewed','NS','Not selected');
INSERT INTO result VALUES (8,'informational','Not_Reviewed','I','Informational');
INSERT INTO result VALUES (9,'fixed','NotAFinding','NF','Fixed');
INSERT INTO status VALUES (0,'saved','Saved');
INSERT INTO status VALUES (1,'submitted','Submitted');
INSERT INTO status VALUES (2,'rejected','Rejected');
INSERT INTO status VALUES (3,'accepted','Accepted');
INSERT INTO department VALUES (0,'Default');
-- IMPORTANT: Remove the last two INSERTs once department endpoints are finished
INSERT INTO department VALUES (10,'Code 10');
INSERT INTO department VALUES (60,'Code 60');
commit;
