name: API state tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "api/source/**"
      - "test/state/**"
      - ".github/workflows/api-state-tests.yml"
jobs:
  api-state-tests:
    name: state tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install api libraries
        working-directory: ./api/source
        run: npm ci
      - name: Install Test dependencies
        working-directory: ./test/state
        run: npm ci
      - name: Install Test dependencies 2
        working-directory: ./test/api
        run: npm ci
      - name: Run state tests
        working-directory: ./test/state
        run: npx mocha --reporter mochawesome --showFailed --exit './mocha/*.test.js'
      - name: Upload mocha test report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: mocha-report-bootstrap
          path: ./test/state/mochawesome-report
  
